In [1]:
#coding=utf-8,
#记得改today,不要白跑啊
import tushare as ts
import pandas as pd
import talib
import time
import datetime
from opendatatools import swindex
import timestamp
from os import walk
ts.set_token('bc406c9fab768c6c699ef450685daed298c5abf2dbdba8da4e810cab')
pro = ts.pro_api()

today=20201106

In [2]:
import baostock as bs
import pandas as pd

# 登陆系统
lg = bs.login()
# 显示登陆返回信息
print('login respond error_code:'+lg.error_code)
print('login respond  error_msg:'+lg.error_msg)

# 获取指数(综合指数、规模指数、一级行业指数、二级行业指数、策略指数、成长指数、价值指数、主题指数)K线数据
# 综合指数，例如：sh.000001 上证指数，sz.399106 深证综指 等；
# 规模指数，例如：sh.000016 上证50，sh.000300 沪深300，sh.000905 中证500，sz.399001 深证成指等；
# 一级行业指数，例如：sh.000037 上证医药，sz.399433 国证交运 等；
# 二级行业指数，例如：sh.000952 300地产，sz.399951 300银行 等；
# 策略指数，例如：sh.000050 50等权，sh.000982 500等权 等；
# 成长指数，例如：sz.399376 小盘成长 等；
# 价值指数，例如：sh.000029 180价值 等；
# 主题指数，例如：sh.000015 红利指数，sh.000063 上证周期 等；

# 详细指标参数，参见“历史行情指标参数”章节
rs = bs.query_history_k_data_plus("000906.sh",
    "date,code,open,high,low,close,preclose,volume,amount,pctChg",
    start_date='2014-01-01', end_date='2020-10-31', frequency="d")
print('query_history_k_data_plus respond error_code:'+rs.error_code)
print('query_history_k_data_plus respond  error_msg:'+rs.error_msg)

# 打印结果集
data_list = []
while (rs.error_code == '0') & rs.next():
    # 获取一条记录，将记录合并在一起
    data_list.append(rs.get_row_data())
result = pd.DataFrame(data_list, columns=rs.fields)
result.to_csv("C:/quant/index/history_Index_k_data.csv", index=False)# 登出系统
bs.logout()

login success!
login respond error_code:0
login respond  error_msg:success
query_history_k_data_plus respond error_code:0
query_history_k_data_plus respond  error_msg:success
logout success!

In [3]:
#因为baostock出数据慢，手动输入当日数据后也能算MA

result=pd.read_csv("C:/quant/index/history_Index_k_data.csv")# 登出系统

ma5=talib.SMA(result.close,timeperiod=5)
ma10=talib.SMA(result.close,timeperiod=10)
ma20=talib.SMA(result.close,timeperiod=20)
ma30=talib.SMA(result.close,timeperiod=30)
ma60=talib.SMA(result.close,timeperiod=60)
ma120=talib.SMA(result.close,timeperiod=120)

ema5=talib.SMA(result.close,timeperiod=5)
ema10=talib.SMA(result.close,timeperiod=10)
ema20=talib.SMA(result.close,timeperiod=20)
ema30=talib.SMA(result.close,timeperiod=30)
ema60=talib.SMA(result.close,timeperiod=60)
ema120=talib.SMA(result.close,timeperiod=120)


result['MA5']=ma5
result['MA10']=ma10
result['MA20']=ma20
result['MA30']=ma30
result['MA60']=ma60
result['MA120']=ma120
result['EMA5']=ema5
result['EMA10']=ema10
result['EMA20']=ema20
result['EMA30']=ema30
result['EMA60']=ema60
result['EMA120']=ema120


# 结果集输出到csv文件
result.to_csv("C:/quant/index/history_Index_k_data.csv", index=False)
print(result)

# 登出系统
bs.logout()

            date       code       open       high        low      close  \
0     2014-01-02  sh.000906  2582.9100  2586.9400  2570.9500  2586.0200
1     2014-01-03  sh.000906  2576.6100  2579.2900  2544.5900  2554.8000
2     2014-01-06  sh.000906  2549.4700  2549.4700  2487.0700  2493.4000
3     2014-01-07  sh.000906  2478.0200  2504.6600  2473.2700  2496.8600
4     2014-01-08  sh.000906  2499.3500  2523.1300  2488.0000  2500.8800
...          ...        ...        ...        ...        ...        ...
1658  2020-10-26  sh.000906  4926.6937  4958.5038  4878.0131  4936.0554
1659  2020-10-27  sh.000906  4922.0691  4952.3297  4912.0689  4943.8202
1660  2020-10-28  sh.000906  4946.8813  4993.1433  4922.5219  4978.9404
1661  2020-10-29  sh.000906  4921.3398  5037.3505  4916.0026  5009.2565
1662  2020-10-30  sh.000906  5015.4587  5017.0833  4909.0489  4919.8791

       preclose       volume        amount    pctChg  ...         MA20  \
0     2589.3500   7599455200  8.043002e+10 -0.128607  ...          NaN
1     2586.0200   9460020800  9.359134e+10 -1.207259  ...          NaN
2     2554.8000  10081227200  9.306843e+10 -2.403325  ...          NaN
3     2493.4000   7096172800  7.015324e+10  0.138775  ...          NaN
4     2496.8600   8329229600  8.328050e+10  0.160993  ...          NaN
...         ...          ...           ...       ...  ...          ...
1658  4957.6898  18173623000  2.907741e+11 -0.436381  ...  4974.536495
1659  4936.0554  16824282000  2.759914e+11  0.157308  ...  4972.726250
1660  4943.8202  19559429000  3.308335e+11  0.710386  ...  4975.728945
1661  4978.9404  20970473300  3.620648e+11  0.608887  ...  4979.267785
1662  5009.2565  25192466300  4.072443e+11 -1.784245  ...  4983.309545

             MA30         MA60        MA120        EMA5       EMA10  \
0             NaN          NaN          NaN         NaN         NaN
1             NaN          NaN          NaN         NaN         NaN
2             NaN          NaN          NaN         NaN         NaN
3             NaN          NaN          NaN         NaN         NaN
4             NaN          NaN          NaN  2526.39200         NaN
...           ...          ...          ...         ...         ...
1658  4961.976417  5004.925232  4722.973984  5003.88408  5036.29994
1659  4961.152177  5006.963513  4730.337799  4981.14968  5018.83972
1660  4960.538217  5008.863230  4737.880068  4968.30780  5008.27845
1661  4964.977590  5009.250773  4745.557918  4965.15246  5002.33386
1662  4967.223687  5008.513510  4751.984507  4957.59032  4988.61076

            EMA20        EMA30        EMA60       EMA120
0             NaN          NaN          NaN          NaN
1             NaN          NaN          NaN          NaN
2             NaN          NaN          NaN          NaN
3             NaN          NaN          NaN          NaN
4             NaN          NaN          NaN          NaN
...           ...          ...          ...          ...
1658  4974.536495  4961.976417  5004.925232  4722.973984
1659  4972.726250  4961.152177  5006.963513  4730.337799
1660  4975.728945  4960.538217  5008.863230  4737.880068
1661  4979.267785  4964.977590  5009.250773  4745.557918
1662  4983.309545  4967.223687  5008.513510  4751.984507

[1663 rows x 22 columns]
logout failed!

In [4]:

pool = pro.stock_basic()
pool.head(5)
writer = pd.ExcelWriter('C:/quant/list/list.xlsx') 
pool.to_excel(writer,'Sheet1')
writer.save()
writer.close()

In [5]:

#从TUSHARE获取申万一级行业列表及其对应股票
Sdf1 = pro.index_classify(level='L1', src='SW')
Sdf1.to_csv('C:/quant/swsindex/L1.csv',index=False,encoding='utf-8-sig') 
#获取申万二级行业列表
Sdf2 = pro.index_classify(level='L2', src='SW')
Sdf2.dropna()
Sdf2['index_code']=Sdf2['index_code'].str.split('.', 2).str[0]
Sdf2.to_csv('C:/quant/swsindex/L2.csv',index=False,encoding='utf-8-sig')

#获取申万三级级行业列表
Sdf3 = pro.index_classify(level='L3', src='SW')
Sdf3.dropna()
Sdf3['index_code']=Sdf3['index_code'].str.split('.', 2).str[0]

Sdf3.to_csv('C:/quant/swsindex/L3.csv',index=False,encoding='utf-8-sig') 
#Sdf3.head(10)
#SW1=pd.merge(Sdf1,Sdf2,how='right',on=['index_code','index_code'])
#SW2=pd.merge(SW1,Sdf2,how='right',on=['index_code','index_code'])

In [6]:
%%time
#2级行业对应个股
L2stocklist=pd.DataFrame()
for i in Sdf2.index_code:
    time.sleep(0.3)
    X=str(i)
    df23, msg = swindex.get_index_cons(X)
    df23['index_code']=X
    df23.rename(columns={'stock_code':'ts_code'}, inplace = True)
    #df23=df23.drop(['start_date','weight'],axis=1)
    L2stocklist=L2stocklist.append(df23)
L2stocklist=pd.merge(L2stocklist,Sdf2,how='left',on='index_code')
L2stocklist

Wall time: 41.6 s

,ts_code,stock_name,start_date,weight,index_code,industry_name,level
0,600759,洲际油气,2015-07-01 00:00:00,9.9323,801023,石油开采,L2
1,600777,新潮能源,2017-07-03 00:00:00,27.4387,801023,石油开采,L2
2,601857,中国石油,2008-06-02 00:00:00,62.6289,801023,石油开采,L2
3,000552,靖远煤电,2008-06-02 00:00:00,1.4085,801021,煤炭开采,L2
4,000571,*ST大洲,2011-10-10 00:00:00,0.7144,801021,煤炭开采,L2
...,...,...,...,...,...,...,...
3807,600811,东方集团,2008-06-02 00:00:00,7.6193,801231,综合,L2
3808,600817,ST宏盛,2011-10-10 00:00:00,1.0086,801231,综合,L2
3809,600818,中路股份,2011-10-10 00:00:00,0.7878,801231,综合,L2
3810,603060,国检集团,2016-11-06 18:27:00,1.8584,801231,综合,L2
3811,603183,建研院,2017-08-26 09:17:00,1.1083,801231,综合,L2

In [7]:
%%time
#3级行业对应个股
L3stocklist=pd.DataFrame()
for i in Sdf3.index_code:
    time.sleep(0.3)
    X=str(i)
    df24, msg = swindex.get_index_cons(X)
    df24['index_code']=X
    df24.rename(columns={'stock_code':'ts_code'}, inplace = True)
    #df23=df23.drop(['start_date','weight'],axis=1)
    L3stocklist=L3stocklist.append(df24)
L3stocklist=pd.merge(L3stocklist,Sdf3,how='left',on='index_code')
L3stocklist

Wall time: 1min 25s

,ts_code,stock_name,start_date,weight,index_code,industry_name,level
0,600759,洲际油气,2015-07-01 00:00:00,9.9323,850211,石油开采,L3
1,600777,新潮能源,2017-07-03 00:00:00,27.4387,850211,石油开采,L3
2,601857,中国石油,2008-06-02 00:00:00,62.6289,850211,石油开采,L3
3,000552,靖远煤电,2008-06-02 00:00:00,1.8153,850221,煤炭开采,L3
4,000571,*ST大洲,2011-10-10 00:00:00,0.9208,850221,煤炭开采,L3
...,...,...,...,...,...,...,...
3855,600811,东方集团,2008-06-02 00:00:00,7.6193,852311,综合,L3
3856,600817,ST宏盛,2011-10-10 00:00:00,1.0086,852311,综合,L3
3857,600818,中路股份,2011-10-10 00:00:00,0.7878,852311,综合,L3
3858,603060,国检集团,2016-11-06 18:27:00,1.8584,852311,综合,L3
3859,603183,建研院,2017-08-26 09:17:00,1.1083,852311,综合,L3

In [8]:
L3stocklist.to_csv("C:/quant/index/L3stocklist.csv", index=False,encoding='utf-8-sig')

In [9]:
%%time
#从申银端口通过刚才过滤的2级行业列表获取数据
allindex = pd.DataFrame() 
#L3stocklist=pd.DataFrame()
for i in Sdf2.index_code:
    time.sleep(0.7)
    X=str(i)
    df2, msg = swindex.get_index_daily(X,start_date=20100101,end_date=today)
    df2.to_csv(r'C:/quant/indexdaydate/2020/'+X+'.csv',index=False,encoding='utf-8-sig') 
    df23, msg = swindex.get_index_cons(X)
    df23.rename(columns={'stock_code':'ts_code'}, inplace = True)
    df23.dropna()
    #df23=df23.drop(['start_date','weight'],axis=1)
    
    allindex = allindex.append(df2)
    #L3stocklist=L3stocklist.append(df23)
allindex = allindex.sort_values(by=['index_code','date'],axis=0,ascending=[True,True])

http://www.swsindex.com/excel2.aspx?ctable=swindexhistory&where= swindexcode in ('801023') and BargainDate >= '20100101' and BargainDate <= '20201106'
http://www.swsindex.com/excel2.aspx?ctable=swindexhistory&where= swindexcode in ('801021') and BargainDate >= '20100101' and BargainDate <= '20201106'
http://www.swsindex.com/excel2.aspx?ctable=swindexhistory&where= swindexcode in ('801022') and BargainDate >= '20100101' and BargainDate <= '20201106'
http://www.swsindex.com/excel2.aspx?ctable=swindexhistory&where= swindexcode in ('801024') and BargainDate >= '20100101' and BargainDate <= '20201106'
http://www.swsindex.com/excel2.aspx?ctable=swindexhistory&where= swindexcode in ('801035') and BargainDate >= '20100101' and BargainDate <= '20201106'
http://www.swsindex.com/excel2.aspx?ctable=swindexhistory&where= swindexcode in ('801033') and BargainDate >= '20100101' and BargainDate <= '20201106'
http://www.swsindex.com/excel2.aspx?ctable=swindexhistory&where= swindexcode in ('801034') and BargainDate >= '20100101' and BargainDate <= '20201106'
http://www.swsindex.com/excel2.aspx?ctable=swindexhistory&where= swindexcode in ('801032') and BargainDate >= '20100101' and BargainDate <= '20201106'
http://www.swsindex.com/excel2.aspx?ctable=swindexhistory&where= swindexcode in ('801036') and BargainDate >= '20100101' and BargainDate <= '20201106'
http://www.swsindex.com/excel2.aspx?ctable=swindexhistory&where= swindexcode in ('801037') and BargainDate >= '20100101' and BargainDate <= '20201106'
http://www.swsindex.com/excel2.aspx?ctable=swindexhistory&where= swindexcode in ('801041') and BargainDate >= '20100101' and BargainDate <= '20201106'
http://www.swsindex.com/excel2.aspx?ctable=swindexhistory&where= swindexcode in ('801055') and BargainDate >= '20100101' and BargainDate <= '20201106'
http://www.swsindex.com/excel2.aspx?ctable=swindexhistory&where= swindexcode in ('801053') and BargainDate >= '20100101' and BargainDate <= '20201106'
http://www.swsindex.com/excel2.aspx?ctable=swindexhistory&where= swindexcode in ('801054') and BargainDate >= '20100101' and BargainDate <= '20201106'
http://www.swsindex.com/excel2.aspx?ctable=swindexhistory&where= swindexcode in ('801051') and BargainDate >= '20100101' and BargainDate <= '20201106'
http://www.swsindex.com/excel2.aspx?ctable=swindexhistory&where= swindexcode in ('801711') and BargainDate >= '20100101' and BargainDate <= '20201106'
http://www.swsindex.com/excel2.aspx?ctable=swindexhistory&where= swindexcode in ('801712') and BargainDate >= '20100101' and BargainDate <= '20201106'
http://www.swsindex.com/excel2.aspx?ctable=swindexhistory&where= swindexcode in ('801713') and BargainDate >= '20100101' and BargainDate <= '20201106'
http://www.swsindex.com/excel2.aspx?ctable=swindexhistory&where= swindexcode in ('801721') and BargainDate >= '20100101' and BargainDate <= '20201106'
http://www.swsindex.com/excel2.aspx?ctable=swindexhistory&where= swindexcode in ('801722') and BargainDate >= '20100101' and BargainDate <= '20201106'
http://www.swsindex.com/excel2.aspx?ctable=swindexhistory&where= swindexcode in ('801725') and BargainDate >= '20100101' and BargainDate <= '20201106'
http://www.swsindex.com/excel2.aspx?ctable=swindexhistory&where= swindexcode in ('801723') and BargainDate >= '20100101' and BargainDate <= '20201106'
http://www.swsindex.com/excel2.aspx?ctable=swindexhistory&where= swindexcode in ('801724') and BargainDate >= '20100101' and BargainDate <= '20201106'
http://www.swsindex.com/excel2.aspx?ctable=swindexhistory&where= swindexcode in ('801731') and BargainDate >= '20100101' and BargainDate <= '20201106'
http://www.swsindex.com/excel2.aspx?ctable=swindexhistory&where= swindexcode in ('801732') and BargainDate >= '20100101' and BargainDate <= '20201106'
http://www.swsindex.com/excel2.aspx?ctable=swindexhistory&where= swindexcode in ('801733') and BargainDate >= '20100101' and BargainDate <= '20201106'
http://www.swsindex.com/excel2.aspx?ctable=swindexhistory&where= swindexcode in ('801734') and BargainDate >= '20100101' and BargainDate <= '20201106'
http://www.swsindex.com/excel2.aspx?ctable=swindexhistory&where= swindexcode in ('801072') and BargainDate >= '20100101' and BargainDate <= '20201106'
http://www.swsindex.com/excel2.aspx?ctable=swindexhistory&where= swindexcode in ('801074') and BargainDate >= '20100101' and BargainDate <= '20201106'
http://www.swsindex.com/excel2.aspx?ctable=swindexhistory&where= swindexcode in ('801073') and BargainDate >= '20100101' and BargainDate <= '20201106'
http://www.swsindex.com/excel2.aspx?ctable=swindexhistory&where= swindexcode in ('801075') and BargainDate >= '20100101' and BargainDate <= '20201106'
http://www.swsindex.com/excel2.aspx?ctable=swindexhistory&where= swindexcode in ('801076') and BargainDate >= '20100101' and BargainDate <= '20201106'
http://www.swsindex.com/excel2.aspx?ctable=swindexhistory&where= swindexcode in ('801741') and BargainDate >= '20100101' and BargainDate <= '20201106'
http://www.swsindex.com/excel2.aspx?ctable=swindexhistory&where= swindexcode in ('801742') and BargainDate >= '20100101' and BargainDate <= '20201106'
http://www.swsindex.com/excel2.aspx?ctable=swindexhistory&where= swindexcode in ('801743') and BargainDate >= '20100101' and BargainDate <= '20201106'
http://www.swsindex.com/excel2.aspx?ctable=swindexhistory&where= swindexcode in ('801744') and BargainDate >= '20100101' and BargainDate <= '20201106'
http://www.swsindex.com/excel2.aspx?ctable=swindexhistory&where= swindexcode in ('801094') and BargainDate >= '20100101' and BargainDate <= '20201106'
http://www.swsindex.com/excel2.aspx?ctable=swindexhistory&where= swindexcode in ('801093') and BargainDate >= '20100101' and BargainDate <= '20201106'
http://www.swsindex.com/excel2.aspx?ctable=swindexhistory&where= swindexcode in ('801092') and BargainDate >= '20100101' and BargainDate <= '20201106'
http://www.swsindex.com/excel2.aspx?ctable=swindexhistory&where= swindexcode in ('801881') and BargainDate >= '20100101' and BargainDate <= '20201106'
http://www.swsindex.com/excel2.aspx?ctable=swindexhistory&where= swindexcode in ('801111') and BargainDate >= '20100101' and BargainDate <= '20201106'
http://www.swsindex.com/excel2.aspx?ctable=swindexhistory&where= swindexcode in ('801112') and BargainDate >= '20100101' and BargainDate <= '20201106'
http://www.swsindex.com/excel2.aspx?ctable=swindexhistory&where= swindexcode in ('801131') and BargainDate >= '20100101' and BargainDate <= '20201106'
http://www.swsindex.com/excel2.aspx?ctable=swindexhistory&where= swindexcode in ('801132') and BargainDate >= '20100101' and BargainDate <= '20201106'
http://www.swsindex.com/excel2.aspx?ctable=swindexhistory&where= swindexcode in ('801143') and BargainDate >= '20100101' and BargainDate <= '20201106'
http://www.swsindex.com/excel2.aspx?ctable=swindexhistory&where= swindexcode in ('801141') and BargainDate >= '20100101' and BargainDate <= '20201106'
http://www.swsindex.com/excel2.aspx?ctable=swindexhistory&where= swindexcode in ('801142') and BargainDate >= '20100101' and BargainDate <= '20201106'
http://www.swsindex.com/excel2.aspx?ctable=swindexhistory&where= swindexcode in ('801144') and BargainDate >= '20100101' and BargainDate <= '20201106'
http://www.swsindex.com/excel2.aspx?ctable=swindexhistory&where= swindexcode in ('801203') and BargainDate >= '20100101' and BargainDate <= '20201106'
http://www.swsindex.com/excel2.aspx?ctable=swindexhistory&where= swindexcode in ('801204') and BargainDate >= '20100101' and BargainDate <= '20201106'
http://www.swsindex.com/excel2.aspx?ctable=swindexhistory&where= swindexcode in ('801205') and BargainDate >= '20100101' and BargainDate <= '20201106'
http://www.swsindex.com/excel2.aspx?ctable=swindexhistory&where= swindexcode in ('801202') and BargainDate >= '20100101' and BargainDate <= '20201106'
http://www.swsindex.com/excel2.aspx?ctable=swindexhistory&where= swindexcode in ('801016') and BargainDate >= '20100101' and BargainDate <= '20201106'
http://www.swsindex.com/excel2.aspx?ctable=swindexhistory&where= swindexcode in ('801015') and BargainDate >= '20100101' and BargainDate <= '20201106'

http://www.swsindex.com/excel2.aspx?ctable=swindexhistory&where= swindexcode in ('801011') and BargainDate >= '20100101' and BargainDate <= '20201106'
http://www.swsindex.com/excel2.aspx?ctable=swindexhistory&where= swindexcode in ('801014') and BargainDate >= '20100101' and BargainDate <= '20201106'
http://www.swsindex.com/excel2.aspx?ctable=swindexhistory&where= swindexcode in ('801012') and BargainDate >= '20100101' and BargainDate <= '20201106'
http://www.swsindex.com/excel2.aspx?ctable=swindexhistory&where= swindexcode in ('801013') and BargainDate >= '20100101' and BargainDate <= '20201106'
http://www.swsindex.com/excel2.aspx?ctable=swindexhistory&where= swindexcode in ('801017') and BargainDate >= '20100101' and BargainDate <= '20201106'
http://www.swsindex.com/excel2.aspx?ctable=swindexhistory&where= swindexcode in ('801018') and BargainDate >= '20100101' and BargainDate <= '20201106'
http://www.swsindex.com/excel2.aspx?ctable=swindexhistory&where= swindexcode in ('801123') and BargainDate >= '20100101' and BargainDate <= '20201106'
http://www.swsindex.com/excel2.aspx?ctable=swindexhistory&where= swindexcode in ('801124') and BargainDate >= '20100101' and BargainDate <= '20201106'
http://www.swsindex.com/excel2.aspx?ctable=swindexhistory&where= swindexcode in ('801212') and BargainDate >= '20100101' and BargainDate <= '20201106'
http://www.swsindex.com/excel2.aspx?ctable=swindexhistory&where= swindexcode in ('801213') and BargainDate >= '20100101' and BargainDate <= '20201106'
http://www.swsindex.com/excel2.aspx?ctable=swindexhistory&where= swindexcode in ('801214') and BargainDate >= '20100101' and BargainDate <= '20201106'
http://www.swsindex.com/excel2.aspx?ctable=swindexhistory&where= swindexcode in ('801211') and BargainDate >= '20100101' and BargainDate <= '20201106'
http://www.swsindex.com/excel2.aspx?ctable=swindexhistory&where= swindexcode in ('801215') and BargainDate >= '20100101' and BargainDate <= '20201106'
http://www.swsindex.com/excel2.aspx?ctable=swindexhistory&where= swindexcode in ('801151') and BargainDate >= '20100101' and BargainDate <= '20201106'
http://www.swsindex.com/excel2.aspx?ctable=swindexhistory&where= swindexcode in ('801155') and BargainDate >= '20100101' and BargainDate <= '20201106'
http://www.swsindex.com/excel2.aspx?ctable=swindexhistory&where= swindexcode in ('801152') and BargainDate >= '20100101' and BargainDate <= '20201106'
http://www.swsindex.com/excel2.aspx?ctable=swindexhistory&where= swindexcode in ('801154') and BargainDate >= '20100101' and BargainDate <= '20201106'
http://www.swsindex.com/excel2.aspx?ctable=swindexhistory&where= swindexcode in ('801153') and BargainDate >= '20100101' and BargainDate <= '20201106'
http://www.swsindex.com/excel2.aspx?ctable=swindexhistory&where= swindexcode in ('801156') and BargainDate >= '20100101' and BargainDate <= '20201106'
http://www.swsindex.com/excel2.aspx?ctable=swindexhistory&where= swindexcode in ('801161') and BargainDate >= '20100101' and BargainDate <= '20201106'
http://www.swsindex.com/excel2.aspx?ctable=swindexhistory&where= swindexcode in ('801164') and BargainDate >= '20100101' and BargainDate <= '20201106'
http://www.swsindex.com/excel2.aspx?ctable=swindexhistory&where= swindexcode in ('801163') and BargainDate >= '20100101' and BargainDate <= '20201106'
http://www.swsindex.com/excel2.aspx?ctable=swindexhistory&where= swindexcode in ('801162') and BargainDate >= '20100101' and BargainDate <= '20201106'
http://www.swsindex.com/excel2.aspx?ctable=swindexhistory&where= swindexcode in ('801171') and BargainDate >= '20100101' and BargainDate <= '20201106'
http://www.swsindex.com/excel2.aspx?ctable=swindexhistory&where= swindexcode in ('801175') and BargainDate >= '20100101' and BargainDate <= '20201106'
http://www.swsindex.com/excel2.aspx?ctable=swindexhistory&where= swindexcode in ('801172') and BargainDate >= '20100101' and BargainDate <= '20201106'
http://www.swsindex.com/excel2.aspx?ctable=swindexhistory&where= swindexcode in ('801173') and BargainDate >= '20100101' and BargainDate <= '20201106'
http://www.swsindex.com/excel2.aspx?ctable=swindexhistory&where= swindexcode in ('801174') and BargainDate >= '20100101' and BargainDate <= '20201106'
http://www.swsindex.com/excel2.aspx?ctable=swindexhistory&where= swindexcode in ('801176') and BargainDate >= '20100101' and BargainDate <= '20201106'
http://www.swsindex.com/excel2.aspx?ctable=swindexhistory&where= swindexcode in ('801177') and BargainDate >= '20100101' and BargainDate <= '20201106'
http://www.swsindex.com/excel2.aspx?ctable=swindexhistory&where= swindexcode in ('801178') and BargainDate >= '20100101' and BargainDate <= '20201106'
http://www.swsindex.com/excel2.aspx?ctable=swindexhistory&where= swindexcode in ('801181') and BargainDate >= '20100101' and BargainDate <= '20201106'
http://www.swsindex.com/excel2.aspx?ctable=swindexhistory&where= swindexcode in ('801182') and BargainDate >= '20100101' and BargainDate <= '20201106'
http://www.swsindex.com/excel2.aspx?ctable=swindexhistory&where= swindexcode in ('801081') and BargainDate >= '20100101' and BargainDate <= '20201106'
http://www.swsindex.com/excel2.aspx?ctable=swindexhistory&where= swindexcode in ('801083') and BargainDate >= '20100101' and BargainDate <= '20201106'
http://www.swsindex.com/excel2.aspx?ctable=swindexhistory&where= swindexcode in ('801084') and BargainDate >= '20100101' and BargainDate <= '20201106'
http://www.swsindex.com/excel2.aspx?ctable=swindexhistory&where= swindexcode in ('801082') and BargainDate >= '20100101' and BargainDate <= '20201106'
http://www.swsindex.com/excel2.aspx?ctable=swindexhistory&where= swindexcode in ('801085') and BargainDate >= '20100101' and BargainDate <= '20201106'
http://www.swsindex.com/excel2.aspx?ctable=swindexhistory&where= swindexcode in ('801101') and BargainDate >= '20100101' and BargainDate <= '20201106'
http://www.swsindex.com/excel2.aspx?ctable=swindexhistory&where= swindexcode in ('801222') and BargainDate >= '20100101' and BargainDate <= '20201106'
http://www.swsindex.com/excel2.aspx?ctable=swindexhistory&where= swindexcode in ('801761') and BargainDate >= '20100101' and BargainDate <= '20201106'
http://www.swsindex.com/excel2.aspx?ctable=swindexhistory&where= swindexcode in ('801751') and BargainDate >= '20100101' and BargainDate <= '20201106'
http://www.swsindex.com/excel2.aspx?ctable=swindexhistory&where= swindexcode in ('801752') and BargainDate >= '20100101' and BargainDate <= '20201106'
http://www.swsindex.com/excel2.aspx?ctable=swindexhistory&where= swindexcode in ('801223') and BargainDate >= '20100101' and BargainDate <= '20201106'
http://www.swsindex.com/excel2.aspx?ctable=swindexhistory&where= swindexcode in ('801102') and BargainDate >= '20100101' and BargainDate <= '20201106'
http://www.swsindex.com/excel2.aspx?ctable=swindexhistory&where= swindexcode in ('801192') and BargainDate >= '20100101' and BargainDate <= '20201106'
http://www.swsindex.com/excel2.aspx?ctable=swindexhistory&where= swindexcode in ('801193') and BargainDate >= '20100101' and BargainDate <= '20201106'
http://www.swsindex.com/excel2.aspx?ctable=swindexhistory&where= swindexcode in ('801194') and BargainDate >= '20100101' and BargainDate <= '20201106'
http://www.swsindex.com/excel2.aspx?ctable=swindexhistory&where= swindexcode in ('801191') and BargainDate >= '20100101' and BargainDate <= '20201106'
http://www.swsindex.com/excel2.aspx?ctable=swindexhistory&where= swindexcode in ('801231') and BargainDate >= '20100101' and BargainDate <= '20201106'
Wall time: 8min 10s

In [10]:
#申银源数据格式不对，转换格式
allindex['open']=allindex['open'].astype("float")
allindex['high']=allindex['high'].astype("float")
allindex['low']=allindex['low'].astype("float")
allindex['close']=allindex['close'].astype("float")
allindex['vol']=allindex['vol'].astype("float")
allindex['amount']=allindex['amount'].astype("float")
allindex['change_pct']=allindex['change_pct'].astype("float")
allindex.isnull().sum()

index_code    0
index_name    0
date          0
open          0
high          0
low           0
close         0
vol           0
amount        0
change_pct    0
dtype: int64

In [11]:
#计算申银行业指数MA，MACD
from scipy.stats import rankdata
swsf=allindex[allindex['index_code'].notna()]

close=swsf.close.values
swsf.date=swsf.date.values

diff, dea, my_macd = talib.MACD(close,
                                             fastperiod=12,
                                             slowperiod=26,
#获取均线的数据，通过timeperiod参数来分别获取 5,10,20 日均线的数据。
                                             signalperiod=9)
SMA5=talib.SMA(close,timeperiod=5)
SMA10=talib.SMA(close,timeperiod=10)
SMA20=talib.SMA(close,timeperiod=20)
SMA60=talib.SMA(close,timeperiod=60)
SMA120=talib.SMA(close,timeperiod=120)
SMA350=talib.SMA(close,timeperiod=350)

EMA5=talib.EMA(close,timeperiod=5)
EMA10=talib.EMA(close,timeperiod=10)
EMA20=talib.EMA(close,timeperiod=20)
EMA60=talib.EMA(close,timeperiod=60)
EMA120=talib.EMA(close,timeperiod=120)

swsf['diff']=diff
swsf['dea']=dea
swsf['MACD']=my_macd
swsf['SMA5']=SMA5
swsf['SMA10']=SMA10
swsf['SMA20']=SMA20
swsf['SMA60']=SMA60
swsf['SMA120']=SMA120
swsf['SMA350']=SMA350

swsf['EMA5']=EMA5
swsf['EMA10']=EMA10
swsf['EMA60']=EMA60
swsf['EMA120']=EMA120

swsf['EMA20']=EMA20
swsf['SMACD-K']=(diff-dea)/dea
swsf['C/S']=(close/SMA20-1)*100
swsf['M/L']=(SMA60/SMA120-1)*100
swsf['S/M']=(SMA20/SMA60-1)*100
swsf['BreakSignal-20D']=close/EMA20-1
swsf.reset_index(drop=True, inplace=True)

swsf['dailyamount']=swsf.groupby('date')['amount'].sum()
swsf['indexamount']=swsf.amount/swsf.dailyamount


swsf.loc[swsf['index_code'] == swsf['index_code'].shift(1),'Chg1D']= (swsf.close/swsf.close.shift(1)-1)*100
swsf.loc[swsf['index_code'] == swsf['index_code'].shift(4),'Chg5D']= (swsf.close/swsf.close.shift(4)-1)*100
swsf.loc[swsf['index_code'] == swsf['index_code'].shift(19),'Chg20D']= (swsf.close/swsf.close.shift(19)-1)*100
swsf.loc[swsf['index_code'] == swsf['index_code'].shift(59),'Chg60D']= (swsf.close/swsf.close.shift(59)-1)*100
swsf.loc[swsf['index_code'] == swsf['index_code'].shift(119),'Chg120D']= (swsf.close/swsf.close.shift(119)-1)*100

swsf.fillna(0,inplace=True) #去除null
swsf.loc[(swsf['close']>swsf['EMA20']) & (swsf['close']>swsf['SMA20']) & (swsf['SMA20']>swsf['SMA20'].shift(19)),'K1']=1 #破线拐头
swsf.loc[(swsf['EMA20']>swsf['EMA60']) & (swsf['close']>swsf['EMA20'].shift(19)),'K2']=1 #双均线交叉
swsf.loc[(swsf['EMA20']>swsf['SMA60']) & (swsf['close']>swsf['EMA20'].shift(19)),'K3']=1 
swsf.loc[(swsf['SMA20']>swsf['EMA60']) & (swsf['close']>swsf['SMA20'].shift(19)),'K4']=1 
swsf.loc[(swsf['SMA20']>swsf['SMA60']) & (swsf['close']>swsf['SMA20'].shift(19)),'K5']=1 

swsf.loc[(swsf['close']<swsf['EMA20']) & (swsf['close']<swsf['SMA20']) & (swsf['SMA20']<swsf['SMA20'].shift(19)),'K1']=-1 #空头方向破线拐头
swsf.loc[(swsf['EMA20']<swsf['EMA60']) & (swsf['close']<swsf['EMA20'].shift(19)),'K2']=-1 #双均线交叉
swsf.loc[(swsf['EMA20']<swsf['SMA60']) & (swsf['close']<swsf['EMA20'].shift(19)),'K3']=-1 
swsf.loc[(swsf['SMA20']<swsf['EMA60']) & (swsf['close']<swsf['SMA20'].shift(19)),'K4']=-1 
swsf.loc[(swsf['SMA20']<swsf['SMA60']) & (swsf['close']<swsf['SMA20'].shift(19)),'K5']=-1 
swsf.fillna(0,inplace=True) #去除null
swsf['Indextrendscore-L']=(swsf.K1+swsf.K2+swsf.K3+swsf.K4+swsf.K5)

swsf.head(10)
swsf.to_csv('C:/quant/index/SWoutput.csv',index=False,encoding='utf-8-sig')

In [12]:
BBIndex=allindex[allindex['index_code'].notna()]
BBIndex.loc[BBIndex.close>=BBIndex.open,'Signal']=0
BBIndex.loc[BBIndex.close<BBIndex.open,'Signal']=1
BBIndex['ChangeSignal']=BBIndex.Signal.diff().abs()
BBIndex.ChangeSignal.fillna(0,inplace=True) #解决首行0
BBIndex['BBperiod']=BBIndex.groupby('index_code').ChangeSignal.cumsum()

#板块级别日线涨跌周期

high = BBIndex.groupby(['index_code','BBperiod'])['high'].max().rename('high').reset_index()
low = BBIndex.groupby(['index_code','BBperiod'])['low'].min().rename('low').reset_index()
amount = BBIndex.groupby(['index_code','BBperiod'])['amount'].sum().rename('amount').reset_index()
open1 = BBIndex.groupby(['index_code','index_name','BBperiod'])['open'].first().rename('open').reset_index()
close1 = BBIndex.groupby(['index_code','BBperiod'])['close'].last().rename('close').reset_index()
lastperiod=BBIndex.groupby('index_code').BBperiod.max().rename('lastbar')

BBI2 = pd.merge(open1,close1,how='left',on=('index_code','BBperiod')) 
BBI2 = pd.merge(BBI2,high,how='left',on=('index_code','BBperiod')) 
BBI2 = pd.merge(BBI2,low,how='left',on=('index_code','BBperiod')) 
BBI2 = pd.merge(BBI2,amount,how='left',on=('index_code','BBperiod')) 
BBI2 = pd.merge(BBI2,lastperiod,how='left',on='index_code') 

close=BBI2.close.values
#swsf.date=swsf.date.values

diff, dea, my_macd = talib.MACD(close,
                                             fastperiod=12,
                                             slowperiod=26,
#获取均线的数据，通过timeperiod参数来分别获取 5,10,20 日均线的数据。
                                             signalperiod=9)
BBI2['D-diff']=diff
BBI2['D-dea']=dea
BBI2['D-MACD']=my_macd

BBI2.to_csv('C:/quant/index/SWBBoutput-D.csv',index=False,encoding='utf-8-sig')

BBI2=BBI2[BBI2['BBperiod']==BBI2['lastbar']]
BBI2 = BBI2.sort_values(by=['D-MACD'],axis=0,ascending=[False])

 
BBI2

,index_code,index_name,BBperiod,open,close,high,low,amount,lastbar,D-diff,D-dea,D-MACD
45025,801111,白色家电,1361.0,20934.10,22607.00,22890.47,20795.76,641.54,1361.0,751.463333,471.784275,279.679058
41015,801094,汽车整车,1312.0,8184.67,8112.31,8495.97,7779.04,319.25,1312.0,692.511398,462.268928,230.242470
98589,801712,玻璃制造,826.0,8821.19,9197.21,9532.45,8635.68,100.23,826.0,488.987954,360.962319,128.025635
61507,801156,医疗服务,1260.0,11507.00,11249.44,11626.39,10983.85,211.89,1260.0,466.265616,348.485990,117.779626
47709,801123,饮料制造,1336.0,33625.05,33274.11,33730.31,32823.40,254.00,1336.0,937.944370,841.915319,96.029051
...,...,...,...,...,...,...,...,...,...,...,...,...
56326,801152,生物制品,1276.0,15112.97,14425.49,15419.79,14132.39,489.84,1276.0,-216.355797,-125.352417,-91.003380
107440,801741,航天装备,842.0,11685.01,11446.99,11786.56,11341.75,49.15,842.0,-133.509461,-42.346898,-91.162564
93083,801214,旅游综合,1263.0,13199.19,12702.41,13330.28,12487.86,58.77,1263.0,-123.938080,19.912796,-143.850875
109058,801743,地面兵装,784.0,15199.14,15021.99,15399.88,14848.48,25.31,784.0,-158.770051,-1.934669,-156.835382
83071,801193,券商,710.0,6115.10,5950.38,6154.30,5896.73,354.43,710.0,-1577.578126,-1185.703150,-391.874976

In [13]:
BBWIndex=allindex[allindex['index_code'].notna()]
BBWIndex['year']=BBWIndex.date.dt.isocalendar().year
BBWIndex['week']=BBWIndex.date.dt.isocalendar().week
high = BBWIndex.groupby(['index_code','year','week'])['high'].max().rename('high').reset_index()
low = BBWIndex.groupby(['index_code','year','week'])['low'].min().rename('low').reset_index()
amount = BBWIndex.groupby(['index_code','year','week'])['amount'].sum().rename('amount').reset_index()
open1 = BBWIndex.groupby(['index_code','index_name','year','week'])['open'].first().rename('open').reset_index()
close1 = BBWIndex.groupby(['index_code','year','week'])['close'].last().rename('close').reset_index()

BBWI2 = pd.merge(open1,close1,how='left',on=('index_code','year','week')) 
BBWI2 = pd.merge(BBWI2,high,how='left',on=('index_code','year','week')) 
BBWI2 = pd.merge(BBWI2,low,how='left',on=('index_code','year','week')) 
BBWI2 = pd.merge(BBWI2,amount,how='left',on=('index_code','year','week')) 

BBWI2.loc[BBWI2.close>=BBWI2.open,'Signal']=0
BBWI2.loc[BBWI2.close<BBWI2.open,'Signal']=1
BBWI2['ChangeSignal']=BBWI2.Signal.diff().abs()
BBWI2.ChangeSignal.fillna(0,inplace=True) #解决首行0
BBWI2['BBperiod']=BBWI2.groupby('index_code').ChangeSignal.cumsum()

high2 = BBWI2.groupby(['index_code','BBperiod'])['high'].max().rename('high').reset_index()
low2 = BBWI2.groupby(['index_code','BBperiod'])['low'].min().rename('low').reset_index()
amount2 = BBWI2.groupby(['index_code','BBperiod'])['amount'].sum().rename('amount').reset_index()
open2 = BBWI2.groupby(['index_code','index_name','BBperiod'])['open'].first().rename('open').reset_index()
close2 = BBWI2.groupby(['index_code','BBperiod'])['close'].last().rename('close').reset_index()
lastperiod=BBWI2.groupby('index_code').BBperiod.max().rename('lastbar')

BBWI3 = pd.merge(open2,close2,how='left',on=('index_code','BBperiod')) 
BBWI3 = pd.merge(BBWI3,high2,how='left',on=('index_code','BBperiod')) 
BBWI3 = pd.merge(BBWI3,low2,how='left',on=('index_code','BBperiod')) 
BBWI3 = pd.merge(BBWI3,amount2,how='left',on=('index_code','BBperiod')) 
BBWI3 = pd.merge(BBWI3,lastperiod,how='left',on='index_code') 

close=BBWI3.close.values
#swsf.date=swsf.date.values

diff, dea, my_macd = talib.MACD(close,
                                             fastperiod=12,
                                             slowperiod=26,
#获取均线的数据，通过timeperiod参数来分别获取 5,10,20 日均线的数据。
                                             signalperiod=9)
BBWI3['W-diff']=diff
BBWI3['W-dea']=dea
BBWI3['W-MACD']=my_macd

BBWI3.to_csv('C:/quant/index/SWBBoutput-W.csv',index=False,encoding='utf-8-sig')
BBWI3=BBWI3[BBWI3['BBperiod']==BBWI3['lastbar']]
BBWI3 = BBWI3.sort_values(by=['W-MACD'],axis=0,ascending=[False])

BBWI3

,index_code,index_name,BBperiod,open,close,high,low,amount,lastbar,W-diff,W-dea,W-MACD
10371,801123,饮料制造,294.0,29704.86,33274.11,33831.52,29579.15,5273.26,294.0,3579.126007,2658.470818,920.655189
23010,801733,电源设备,166.0,12398.69,13537.19,14227.82,12131.82,3918.73,166.0,1553.625962,1234.275157,319.350805
9795,801111,白色家电,296.0,19376.22,22607.00,22890.47,19025.24,1670.48,296.0,1268.714761,953.346962,315.367799
8938,801094,汽车整车,294.0,5592.42,8112.31,8495.97,5478.16,3550.38,294.0,479.410673,164.406036,315.004636
21435,801712,玻璃制造,170.0,7485.28,9197.21,9532.45,7391.02,301.71,170.0,911.682377,694.148325,217.534052
...,...,...,...,...,...,...,...,...,...,...,...,...
1907,801017,畜禽养殖,239.0,4193.37,3910.12,4257.89,3838.22,451.49,239.0,-20.292739,78.974864,-99.267603
1107,801014,饲料,293.0,7751.99,7629.49,7924.96,7527.62,150.23,293.0,557.376106,657.069842,-99.693736
21265,801711,水泥制造,168.0,8177.68,8655.82,8755.47,8068.67,255.87,168.0,558.343831,663.816186,-105.472355
2133,801018,动物保健,226.0,8814.02,7803.14,8990.06,7612.43,181.02,226.0,654.291333,761.930573,-107.639239
18079,801193,券商,155.0,6115.10,5950.38,6154.30,5896.73,354.43,155.0,-66.761281,628.931867,-695.693148

In [14]:
BBMIndex=allindex[allindex['index_code'].notna()]
BBMIndex['year']=BBMIndex.date.dt.isocalendar().year
BBMIndex['month']=BBMIndex.date.dt.month
high = BBMIndex.groupby(['index_code','year','month'])['high'].max().rename('high').reset_index()
low = BBMIndex.groupby(['index_code','year','month'])['low'].min().rename('low').reset_index()
amount = BBMIndex.groupby(['index_code','year','month'])['amount'].sum().rename('amount').reset_index()
open1 = BBMIndex.groupby(['index_code','index_name','year','month'])['open'].first().rename('open').reset_index()
close1 = BBMIndex.groupby(['index_code','year','month'])['close'].last().rename('close').reset_index()

BBMI2 = pd.merge(open1,close1,how='left',on=('index_code','year','month')) 
BBMI2 = pd.merge(BBMI2,high,how='left',on=('index_code','year','month')) 
BBMI2 = pd.merge(BBMI2,low,how='left',on=('index_code','year','month')) 
BBMI2 = pd.merge(BBMI2,amount,how='left',on=('index_code','year','month')) 

BBMI2.loc[BBMI2.close>=BBMI2.open,'Signal']=0
BBMI2.loc[BBMI2.close<BBMI2.open,'Signal']=1
BBMI2['ChangeSignal']=BBMI2.Signal.diff().abs()
BBMI2.ChangeSignal.fillna(0,inplace=True) #解决首行0
BBMI2['BBperiod']=BBMI2.groupby('index_code').ChangeSignal.cumsum()

high2 = BBMI2.groupby(['index_code','BBperiod'])['high'].max().rename('high').reset_index()
low2 = BBMI2.groupby(['index_code','BBperiod'])['low'].min().rename('low').reset_index()
amount2 = BBMI2.groupby(['index_code','BBperiod'])['amount'].sum().rename('amount').reset_index()
open2 = BBMI2.groupby(['index_code','index_name','BBperiod'])['open'].first().rename('open').reset_index()
close2 = BBMI2.groupby(['index_code','BBperiod'])['close'].last().rename('close').reset_index()
lastperiod=BBMI2.groupby('index_code').BBperiod.max().rename('lastbar')

BBMI3 = pd.merge(open2,close2,how='left',on=('index_code','BBperiod')) 
BBMI3 = pd.merge(BBMI3,high2,how='left',on=('index_code','BBperiod')) 
BBMI3 = pd.merge(BBMI3,low2,how='left',on=('index_code','BBperiod')) 
BBMI3 = pd.merge(BBMI3,amount2,how='left',on=('index_code','BBperiod')) 
BBMI3 = pd.merge(BBMI3,lastperiod,how='left',on='index_code') 

close=BBMI3.close.values
#swsf.date=swsf.date.values

diff, dea, my_macd = talib.MACD(close,
                                             fastperiod=12,
                                             slowperiod=26,
#获取均线的数据，通过timeperiod参数来分别获取 5,10,20 日均线的数据。
                                             signalperiod=9)
BBMI3['M-diff']=diff
BBMI3['M-dea']=dea
BBMI3['M-MACD']=my_macd

BBMI3.to_csv('C:/quant/index/SWBBoutput-M.csv',index=False,encoding='utf-8-sig')

BBMI3=BBMI3[BBMI3['BBperiod']==BBMI3['lastbar']]
BBMI3 = BBMI3.sort_values(by=['M-MACD'],axis=0,ascending=[False])

BBMI3

,index_code,index_name,BBperiod,open,close,high,low,amount,lastbar,M-diff,M-dea,M-MACD
2257,801123,饮料制造,60.0,30553.55,20689.49,33831.52,20175.40,5157.88,60.0,4161.682812,3585.527161,576.155652
2685,801152,生物制品,60.0,8550.69,8761.44,8888.95,8385.74,134.52,60.0,1499.435846,1083.044770,416.391075
2751,801153,医疗器械,66.0,5657.76,5842.01,5893.72,5584.99,115.54,66.0,926.487588,603.150575,323.337012
4566,801214,旅游综合,69.0,6570.56,6641.09,6661.76,6526.73,23.09,69.0,1613.345760,1292.035824,321.309936
5171,801733,电源设备,38.0,11473.48,7032.65,14227.82,6860.10,16456.01,38.0,438.098692,133.197279,304.901414
...,...,...,...,...,...,...,...,...,...,...,...,...
1959,801094,汽车整车,60.0,4107.88,4422.64,8495.97,3996.81,10769.63,60.0,-240.081210,-159.045813,-81.035398
3502,801174,机场,70.0,7131.84,8789.44,8846.64,6717.95,84.19,70.0,784.822731,888.652539,-103.829808
4270,801204,专业零售,38.0,9042.62,7966.11,9881.35,7777.85,386.27,38.0,-116.516800,2.936327,-119.453128
4068,801193,券商,39.0,6115.10,5950.38,6154.30,5896.73,354.43,39.0,726.357039,869.380635,-143.023596
5055,801725,园林工程,30.0,5525.71,5516.57,5800.29,5363.72,88.81,30.0,-914.965531,-289.150978,-625.814553

In [15]:
IndexReport=swsf[['date','index_code','index_name','close','Chg1D','Chg5D','Chg20D','Chg60D','Chg120D','C/S','S/M','M/L','K1','Indextrendscore-L']]
lastday=IndexReport.date.max()
IndexReport=IndexReport[IndexReport.date==lastday]
IDReport=BBI2[['index_code','D-diff','D-dea','D-MACD']]
IWReport=BBWI3[['index_code','W-diff','W-dea','W-MACD']]
IMReport=BBMI3[['index_code','M-diff','M-dea','M-MACD']]
IndexReport=pd.merge(IndexReport,IDReport,how='left',on='index_code')
IndexReport=pd.merge(IndexReport,IWReport,how='left',on='index_code')
IndexReport=pd.merge(IndexReport,IMReport,how='left',on='index_code')

IndexReport.to_csv('C:/quant/output/Indexoutput.csv',index=False,encoding='utf-8-sig') 
IndexReport

,date,index_code,index_name,close,Chg1D,Chg5D,Chg20D,Chg60D,Chg120D,C/S,...,Indextrendscore-L,D-diff,D-dea,D-MACD,W-diff,W-dea,W-MACD,M-diff,M-dea,M-MACD
0,2020-11-06,801011,林业,1042.10,0.109514,2.012648,-10.772234,-24.908847,14.842080,-2.849717,...,-5.0,-52.978666,-39.445832,-13.532833,-27.917732,-31.334403,3.416670,-196.517060,-185.907401,-10.609658
1,2020-11-06,801012,农产品加工,2695.51,0.724180,3.911659,-6.639305,-13.429255,19.643047,-0.989313,...,-5.0,-45.818996,-19.670094,-26.148902,207.688474,207.578847,0.109627,14.965228,-24.221025,39.186252
2,2020-11-06,801013,农业综合,2032.70,-4.230409,0.532659,-1.221669,19.409035,18.410169,-2.907775,...,-1.0,9.827832,23.612939,-13.785107,41.997816,-9.383557,51.381373,-147.798322,-146.742062,-1.056260
3,2020-11-06,801014,饲料,7629.49,-2.350527,-0.963818,-7.099622,-21.167644,-0.395572,-3.654242,...,-5.0,-253.566781,-219.839851,-33.726930,557.376106,657.069842,-99.693736,1121.941585,892.451816,229.489769
4,2020-11-06,801015,渔业,759.32,-1.491918,2.588629,-11.695682,-17.537820,2.716303,-5.529190,...,-5.0,-32.304893,-24.712535,-7.592357,-4.006308,-3.203075,-0.803233,-222.871955,-230.732333,7.860378
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
93,2020-11-06,801744,船舶制造,2275.74,-0.814149,3.662303,-7.590167,-14.697923,15.017689,-2.762381,...,-5.0,-47.470058,-32.484137,-14.985921,35.288610,18.357184,16.931425,-615.163847,-857.735784,242.571938
94,2020-11-06,801751,营销传播,4024.79,0.109193,3.539566,8.611961,27.049149,38.188317,2.624533,...,5.0,133.708072,132.524382,1.183690,251.211791,158.452352,92.759439,-429.081991,-549.478374,120.396383
95,2020-11-06,801752,互联网传媒,1267.73,-0.908274,1.484162,-10.446380,-15.852671,9.338911,-3.893010,...,-5.0,-47.143979,-35.107448,-12.036532,77.730595,99.701993,-21.971399,-213.028990,-297.054741,84.025751
96,2020-11-06,801761,文化传媒,1832.97,-0.601929,1.872982,-5.919037,-7.691959,6.361484,-2.087446,...,-5.0,-36.618029,-29.330815,-7.287215,29.642584,31.311397,-1.668813,-311.731609,-321.110097,9.378488
97,2020-11-06,801881,其他交运设备,2191.50,-2.089998,2.817331,13.552165,27.257418,87.642883,5.083419,...,5.0,119.532423,115.197596,4.334827,181.371712,87.191729,94.179983,-89.455733,-142.818763,53.363030

In [16]:

#从TUSHARE端口获取成分股
ISindex = pd.DataFrame() 

for i in Sdf1.index_code:
    time.sleep(0.7)
    Tf=pro.index_member(index_code=i)    
    ISindex = ISindex.append(Tf)

ISindex.to_csv(r'C:/quant/swsindex/total.csv') 
ISindex.rename(columns={'con_code':'ts_code'}, inplace = True)
ISindex=pd.merge(ISindex,Sdf2,how='left',on='index_code')
ISindex=ISindex.drop(["in_date",'out_date','level'],axis=1)

ISindex

     index_code    ts_code industry_name
0     801020.SI  600348.SH           NaN
1     801020.SI  600121.SH           NaN
2     801020.SI  600157.SH           NaN
3     801020.SI  600792.SH           NaN
4     801020.SI  600123.SH           NaN
...         ...        ...           ...
3730  801230.SI  600175.SH           NaN
3731  801230.SI  600149.SH           NaN
3732  801230.SI  600234.SH           NaN
3733  801230.SI  300688.SZ           NaN
3734  801230.SI  603183.SH           NaN

[3735 rows x 3 columns]

In [17]:

#从TUSHARE端口获取成分股
ISindex3 = pd.DataFrame() 

#for i in Sdf3.index_code:
 #   time.sleep(0.7)
Tf=pro.index_member(index_code='850553')    
   # ISindex3 = ISindex3.append(Tf)

#ISindex3.rename(columns={'con_code':'ts_code'}, inplace = True)
#ISindex3=pd.merge(ISindex3,Sdf3,how='left',on='index_code')
#ISindex3=ISindex3.drop(["in_date",'out_date','level'],axis=1)
#ISindex3.to_csv(r'C:/quant/swsindex/L3.csv') 

Tf

Empty DataFrame
Columns: [index_code, con_code, in_date, out_date]
Index: []

In [18]:
latestday=max(swsf.date)
ETF=swsf[swsf.date==latestday]
ETF=ETF[['index_code','K1','Indextrendscore-L']]
ISindex['index_code']=ISindex['index_code'].str.split('.', 2).str[0]

ISindex2 = pd.merge(ISindex, ETF, how='left',on='index_code') #分段信息
ISindex2

     index_code    ts_code industry_name  K1  Indextrendscore-L
0        801020  600348.SH           NaN NaN                NaN
1        801020  600121.SH           NaN NaN                NaN
2        801020  600157.SH           NaN NaN                NaN
3        801020  600792.SH           NaN NaN                NaN
4        801020  600123.SH           NaN NaN                NaN
...         ...        ...           ...  ..                ...
3730     801230  600175.SH           NaN NaN                NaN
3731     801230  600149.SH           NaN NaN                NaN
3732     801230  600234.SH           NaN NaN                NaN
3733     801230  300688.SZ           NaN NaN                NaN
3734     801230  603183.SH           NaN NaN                NaN

[3735 rows x 5 columns]

In [19]:
#tushare交易日历
calendar = pro.query('trade_cal', start_date='20201105', end_date=today)
calendar = calendar.drop(calendar[calendar['is_open']==0].index)
calendar

  exchange  cal_date  is_open
0      SSE  20201105        1
1      SSE  20201106        1

In [20]:

#从tushare下载日数据

for i in calendar.cal_date:  #range(20201021,today+1):
    time.sleep(0.75)
    print (i) 
    x=str(i)
    df = pro.daily(trade_date=x) #个股数据
    Adf = pro.query('adj_factor', trade_date=x) #复权因子
    Adf.rename(columns={'trade_date':'trade_date_x'}, inplace = True)
    Adf.adj_factor.fillna(0,inplace=True)


    Mdf = pro.moneyflow(trade_date=x) #个股资金流向，出韭菜指数
    X1=pd.merge(df,Mdf,on='ts_code')
    X1=pd.merge(X1,Adf,on=['ts_code','trade_date_x'])

    mf = pro.margin(trade_date=x)#融资融券数据
    GCdf = pro.repo_daily(ts_code='204001.sh',trade_date=x) # 逆回购数据
    #HSdf = pro.repo_daily(ts_code='000906.sh',trade_date=x) # 逆回购数据

    #X2=pd.merge(mf,GCdf,on='trade_date')

    #df2 = pro.index_dailybasic(start_date=x,fields='ts_code,trade_date,turnover_rate,pe,pe_ttm')
    #pe = df2['pe_ttm']


    writer1 = X1.to_csv('C:/quant/daydate/recentdecade/'+x + '.csv') 
    writer2 = GCdf.to_csv('C:/quant/GCdata/2020/'+x + '.csv') 
    writer3 = mf.to_csv('C:/quant/financing/2020/'+x + '.csv') #要晚一天出，所以不能合并
    #writer4 = HSdf.to_csv('C:/quant/index/2020/'+x + '.csv') #要晚一天出，所以不能合并


   # df.to_csv(writer)
  #  writer.save()
   # writer.close()

20201105
20201106

In [21]:
'''#生成15-20年单年数据
import pandas as pd
import datetime
import numpy as np
from os import walk
for root,dirs,files in walk(r'C:/quant/daydate/2020/',topdown=False):
    num = len(files)
    alldata = pd.DataFrame() 
for i in range(num):
    newdata = pd.read_csv(r'C:/quant/daydate/2020/%s'%files[i])
    
    alldata = alldata.append(newdata)
alldata = alldata.sort_values(by=['ts_code','trade_date_x'],axis=0,ascending=[True,True])
alldata.reset_index(drop=True, inplace=True)
alldata.to_csv('C:/quant/daydate/summary/2020summary.csv') 
'''

"#生成15-20年单年数据\nimport pandas as pd\nimport datetime\nimport numpy as np\nfrom os import walk\nfor root,dirs,files in walk(r'C:/quant/daydate/2020/',topdown=False):\n    num = len(files)\n    alldata = pd.DataFrame() \nfor i in range(num):\n    newdata = pd.read_csv(r'C:/quant/daydate/2020/%s'%files[i])\n    \n    alldata = alldata.append(newdata)\nalldata = alldata.sort_values(by=['ts_code','trade_date_x'],axis=0,ascending=[True,True])\nalldata.reset_index(drop=True, inplace=True)\nalldata.to_csv('C:/quant/daydate/summary/2020summary.csv') \n"

In [22]:

%%time
#生成totalsummary原始版

for root,dirs,files in walk(r'C:/quant/daydate/recentdecade',topdown=False):
    num = len(files)
    Salldata = pd.DataFrame()

for i in range(num):
    newdata = pd.read_csv(r'C:/quant/daydate/recentdecade/%s'%files[i])
    newdata = newdata.drop(newdata.columns[0],axis=1) #去除tushare源生数据首列index

    Salldata = Salldata.append(newdata)
Salldata = Salldata.sort_values(by=['ts_code','trade_date_x'],axis=0,ascending=[True,True])
Salldata.reset_index(drop=True, inplace=True)
Salldata.drop_duplicates()
Salldata.to_csv('C:/quant/daydate/summary/totalsummary.csv') 
Salldata

Wall time: 30min 9s

,ts_code,trade_date_x,open,high,low,close,pre_close,change,pct_chg,vol,...,buy_lg_amount,sell_lg_vol,sell_lg_amount,buy_elg_vol,buy_elg_amount,sell_elg_vol,sell_elg_amount,net_mf_vol,net_mf_amount,adj_factor
0,000001.SZ,20170103,9.11,9.18,9.09,9.16,9.10,0.06,0.6600,459840.49,...,12849.44,142781,13065.97,113061,10343.41,130706,11939.93,71350,6531.67,104.758
1,000001.SZ,20170104,9.15,9.18,9.14,9.16,9.16,0.00,0.0000,449329.53,...,11503.47,128951,11810.56,104137,9540.33,176725,16185.19,-6884,-608.63,104.758
2,000001.SZ,20170105,9.17,9.18,9.15,9.17,9.16,0.01,0.1100,344372.91,...,8720.31,111251,10200.48,59032,5413.23,66840,6128.81,17325,1604.98,104.758
3,000001.SZ,20170106,9.17,9.17,9.11,9.13,9.17,-0.04,-0.4400,358154.20,...,8301.36,96851,8851.30,94131,8599.49,75682,6910.19,-137025,-12502.51,104.758
4,000001.SZ,20170109,9.13,9.17,9.11,9.15,9.13,0.02,0.2200,361081.57,...,6681.79,102405,9358.58,116900,10686.08,96489,8817.27,-38202,-3471.15,104.758
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2345247,688981.SH,20201102,63.44,63.47,60.35,62.65,62.24,0.41,0.6587,511623.09,...,120185.20,171303,106345.67,89140,55622.43,126488,78428.69,-20038,-11856.99,1.000
2345248,688981.SH,20201103,62.50,65.47,62.34,64.56,62.65,1.91,3.0487,550197.05,...,147040.39,199883,129034.01,99171,64108.08,101480,65476.69,51522,33595.56,1.000
2345249,688981.SH,20201104,64.20,65.25,62.51,63.00,64.56,-1.56,-2.4164,460192.42,...,72350.27,136837,87150.87,57213,36530.15,91734,58296.44,-42276,-26532.14,1.000
2345250,688981.SH,20201105,65.00,65.50,63.56,64.84,63.00,1.84,2.9206,414596.41,...,98726.41,144104,93106.71,101078,65479.96,73173,47270.95,49461,32197.90,1.000
2345251,688981.SH,20201106,64.59,65.65,64.02,64.95,64.84,0.11,0.1696,358663.55,...,83456.40,122543,79412.41,67930,44083.48,89107,57705.37,16287,10816.59,1.000

In [23]:
'''%%time
for root,dirs,files in walk(r'C:/quant/daydate/temp',topdown=False):
    num = len(files)
    alldata = pd.read_csv(r'C:/quant/daydate/summary/totalsummary.csv')

for i in range(num):
    newdata = pd.read_csv(r'C:/quant/daydate/temp/%s'%files[i])
    newdata = newdata.drop(newdata.columns[0],axis=1) #去除tushare源生数据首列index
    newdata=newdata.dropna(subset=["trade_date_x"])
    alldata = alldata.append(newdata)
alldata = alldata.dropna(subset=['trade_date_x'])
alldata = alldata.sort_values(by=['ts_code','trade_date_x'],axis=0,ascending=[True,True])
alldata.reset_index(drop=True, inplace=True)
alldata.to_csv('C:/quant/daydate/summary/totalsummary.csv') 
alldata'''

'%%time\nfor root,dirs,files in walk(r\'C:/quant/daydate/temp\',topdown=False):\n    num = len(files)\n    alldata = pd.read_csv(r\'C:/quant/daydate/summary/totalsummary.csv\')\n\nfor i in range(num):\n    newdata = pd.read_csv(r\'C:/quant/daydate/temp/%s\'%files[i])\n    newdata = newdata.drop(newdata.columns[0],axis=1) #去除tushare源生数据首列index\n    newdata=newdata.dropna(subset=["trade_date_x"])\n    alldata = alldata.append(newdata)\nalldata = alldata.dropna(subset=[\'trade_date_x\'])\nalldata = alldata.sort_values(by=[\'ts_code\',\'trade_date_x\'],axis=0,ascending=[True,True])\nalldata.reset_index(drop=True, inplace=True)\nalldata.to_csv(\'C:/quant/daydate/summary/totalsummary.csv\') \nalldata'

In [24]:
%%time
S=Salldata
pd.isnull(S).sum()
S['date']=S.trade_date_x.astype(str)
S.date=S.date.str.split('.', 2).str[0]
S.date=pd.to_datetime(S.date)
S.open=S.open.fillna(method='ffill')
S.close=S.close.fillna(method='ffill') #防停牌无数据
S.high=S.high.fillna(method='ffill')
S.low=S.low.fillna(method='ffill')
#S.amount=S.amount.fillna(0,inplace=True)


latestday=S.date.max()
S.adj_factor.fillna(1,inplace=True)
S.loc[S['date']==latestday,'now_adj']=S['adj_factor'] # 最新复权因子
S.now_adj=S.now_adj.fillna(method='bfill')

#S.loc[S['ts_code']==S['ts_code'].shift(1),'now_adj']=S.now_adj.shift(1) # 最新复权因子

S['close_qfq'] = S['close'] * S['adj_factor'] / S.now_adj  # 前复权 当日收盘价 × 当日复权因子 / 最新复权因子
#alldata.to_csv('C:/quant/index/2020/test.csv') 

S

Wall time: 12.8 s

,ts_code,trade_date_x,open,high,low,close,pre_close,change,pct_chg,vol,...,buy_elg_vol,buy_elg_amount,sell_elg_vol,sell_elg_amount,net_mf_vol,net_mf_amount,adj_factor,date,now_adj,close_qfq
0,000001.SZ,20170103,9.11,9.18,9.09,9.16,9.10,0.06,0.6600,459840.49,...,113061,10343.41,130706,11939.93,71350,6531.67,104.758,2017-01-03,111.048,8.641158
1,000001.SZ,20170104,9.15,9.18,9.14,9.16,9.16,0.00,0.0000,449329.53,...,104137,9540.33,176725,16185.19,-6884,-608.63,104.758,2017-01-04,111.048,8.641158
2,000001.SZ,20170105,9.17,9.18,9.15,9.17,9.16,0.01,0.1100,344372.91,...,59032,5413.23,66840,6128.81,17325,1604.98,104.758,2017-01-05,111.048,8.650591
3,000001.SZ,20170106,9.17,9.17,9.11,9.13,9.17,-0.04,-0.4400,358154.20,...,94131,8599.49,75682,6910.19,-137025,-12502.51,104.758,2017-01-06,111.048,8.612857
4,000001.SZ,20170109,9.13,9.17,9.11,9.15,9.13,0.02,0.2200,361081.57,...,116900,10686.08,96489,8817.27,-38202,-3471.15,104.758,2017-01-09,111.048,8.631724
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2345247,688981.SH,20201102,63.44,63.47,60.35,62.65,62.24,0.41,0.6587,511623.09,...,89140,55622.43,126488,78428.69,-20038,-11856.99,1.000,2020-11-02,1.000,62.650000
2345248,688981.SH,20201103,62.50,65.47,62.34,64.56,62.65,1.91,3.0487,550197.05,...,99171,64108.08,101480,65476.69,51522,33595.56,1.000,2020-11-03,1.000,64.560000
2345249,688981.SH,20201104,64.20,65.25,62.51,63.00,64.56,-1.56,-2.4164,460192.42,...,57213,36530.15,91734,58296.44,-42276,-26532.14,1.000,2020-11-04,1.000,63.000000
2345250,688981.SH,20201105,65.00,65.50,63.56,64.84,63.00,1.84,2.9206,414596.41,...,101078,65479.96,73173,47270.95,49461,32197.90,1.000,2020-11-05,1.000,64.840000
2345251,688981.SH,20201106,64.59,65.65,64.02,64.95,64.84,0.11,0.1696,358663.55,...,67930,44083.48,89107,57705.37,16287,10816.59,1.000,2020-11-06,1.000,64.950000

In [25]:
%%time
from scipy.stats import rankdata
df=S[S['ts_code'].notna()]

close=df.close_qfq
diff, dea, my_macd = talib.MACD(close,
                                             fastperiod=12,
                                             slowperiod=26,
#获取均线的数据，通过timeperiod参数来分别获取 5,10,20 日均线的数据。
                                             signalperiod=9)
SMA5=talib.SMA(close,timeperiod=5)
SMA10=talib.SMA(close,timeperiod=10)
SMA20=talib.SMA(close,timeperiod=20)
SMA60=talib.SMA(close,timeperiod=60)
SMA120=talib.SMA(close,timeperiod=120)

EMA5=talib.EMA(close,timeperiod=5)
EMA10=talib.EMA(close,timeperiod=10)
EMA20=talib.EMA(close,timeperiod=20)
EMA60=talib.EMA(close,timeperiod=60)
EMA120=talib.EMA(close,timeperiod=120)

df['diff']=diff
df['dea']=dea
df['MACD']=my_macd
df['SMA5']=SMA5
df['SMA10']=SMA10
df['SMA20']=SMA20
df['SMA60']=SMA60
df['SMA120']=SMA120

df['EMA5']=EMA5
df['EMA10']=EMA10
df['EMA60']=EMA60
df['EMA120']=EMA120

df['EMA20']=EMA20
df['SMACD-K']=(diff-dea)/dea
df['C/S']=(close/SMA20-1)*100
df['M/L']=(SMA60/SMA120-1)*100
df['S/M']=(SMA20/SMA60-1)*100
df.reset_index(drop=True, inplace=True)

df.loc[df['ts_code'] == df['ts_code'].shift(4),'Chg5D']= (df.close_qfq/df.close_qfq.shift(4)-1)*100
df.loc[df['ts_code'] == df['ts_code'].shift(9),'Chg10D']= (df.close_qfq/df.close_qfq.shift(9)-1)*100
df.loc[df['ts_code'] == df['ts_code'].shift(19),'Chg20D']= (df.close_qfq/df.close_qfq.shift(19)-1)*100
df.loc[df['ts_code'] == df['ts_code'].shift(59),'Chg60D']= (df.close_qfq/df.close_qfq.shift(59)-1)*100
df.loc[df['ts_code'] == df['ts_code'].shift(119),'Chg120D']= (df.close_qfq/df.close_qfq.shift(119)-1)*100

df['ATR'] = talib.ATR(df.high.values,df.low.values,df.pre_close.values, timeperiod=20)


df.fillna(0,inplace=True) #去除null
df.loc[(df['close_qfq']>df['EMA20']) & (df['close_qfq']>df['SMA20']) & (df['SMA20']>df['SMA20'].shift(19)),'kl1']=1 #破线拐头
df.loc[(df['EMA20']>df['EMA60']) & (df['close_qfq']>df['EMA20'].shift(19)),'K2']=1 #双均线交叉
df.loc[(df['EMA20']>df['SMA60']) & (df['close_qfq']>df['EMA20'].shift(19)),'K3']=1 
df.loc[(df['SMA20']>df['EMA60']) & (df['close_qfq']>df['SMA20'].shift(19)),'K4']=1 
df.loc[(df['SMA20']>df['SMA60']) & (df['close_qfq']>df['SMA20'].shift(19)),'K5']=1 

df.loc[(df['close_qfq']<df['EMA20']) & (df['close_qfq']<df['SMA20']) & (df['SMA20']<df['SMA20'].shift(19)),'kl1']=-1 #空头方向破线拐头
df.loc[(df['EMA20']<df['EMA60']) & (df['close_qfq']<df['EMA20'].shift(19)),'K2']=-1 #双均线交叉
df.loc[(df['EMA20']<df['SMA60']) & (df['close_qfq']<df['EMA20'].shift(19)),'K3']=-1 
df.loc[(df['SMA20']<df['EMA60']) & (df['close_qfq']<df['SMA20'].shift(19)),'K4']=-1 
df.loc[(df['SMA20']<df['SMA60']) & (df['close_qfq']<df['SMA20'].shift(19)),'K5']=-1 
df.fillna(0,inplace=True) #去除null
df['trendscore-L']=(df.kl1+df.K2+df.K3+df.K4+df.K5)

df.loc[(df['close_qfq']>df['EMA10']) & (df['close_qfq']>df['SMA10']) & (df['SMA10']>df['SMA10'].shift(19)),'ks1']=1 #破线拐头
df.loc[(df['EMA10']>df['EMA20']) & (df['close_qfq']>df['EMA10'].shift(19)),'KK2']=1 #双均线交叉
df.loc[(df['EMA10']>df['SMA20']) & (df['close_qfq']>df['EMA10'].shift(19)),'KK3']=1 
df.loc[(df['SMA10']>df['EMA20']) & (df['close_qfq']>df['SMA10'].shift(19)),'KK4']=1 
df.loc[(df['SMA10']>df['SMA20']) & (df['close_qfq']>df['SMA10'].shift(19)),'KK5']=1 

df.loc[(df['close_qfq']<df['EMA10']) & (df['close_qfq']<df['SMA10']) & (df['SMA10']<df['SMA10'].shift(19)),'ks1']=-1 #空头方向破线拐头
df.loc[(df['EMA10']<df['EMA20']) & (df['close_qfq']<df['EMA10'].shift(19)),'KK2']=-1 #双均线交叉
df.loc[(df['EMA10']<df['SMA20']) & (df['close_qfq']<df['EMA10'].shift(19)),'KK3']=-1 
df.loc[(df['SMA10']<df['EMA20']) & (df['close_qfq']<df['SMA10'].shift(19)),'KK4']=-1 
df.loc[(df['SMA10']<df['SMA20']) & (df['close_qfq']<df['SMA10'].shift(19)),'KK5']=-1 
df.fillna(0,inplace=True) #去除null
df['trendscore-S']=(df.ks1+df.KK2+df.KK3+df.KK4+df.KK5)
df = pd.merge(df, ISindex, how='left',on='ts_code') 

df=df[['date','ts_code','open','close_qfq','high','low','amount','pct_chg','ATR','Chg5D','Chg20D','Chg60D','Chg120D','C/S','S/M','M/L','kl1','trendscore-L','SMA20','SMA60','SMA120','EMA20','EMA60','EMA120']]

df.head(10)

Wall time: 1min 34s

,date,ts_code,open,close_qfq,high,low,amount,pct_chg,ATR,Chg5D,...,S/M,M/L,kl1,trendscore-L,SMA20,SMA60,SMA120,EMA20,EMA60,EMA120
0,2017-01-03,000001.SZ,9.11,8.641158,9.18,9.09,420595.176,0.66,0.0,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,2017-01-04,000001.SZ,9.15,8.641158,9.18,9.14,411503.444,0.00,0.0,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,2017-01-05,000001.SZ,9.17,8.650591,9.18,9.15,315769.693,0.11,0.0,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,2017-01-06,000001.SZ,9.17,8.612857,9.17,9.11,327176.433,-0.44,0.0,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,2017-01-09,000001.SZ,9.13,8.631724,9.17,9.11,329994.604,0.22,0.0,-0.109170,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,2017-01-10,000001.SZ,9.15,8.631724,9.16,9.14,220575.131,0.00,0.0,-0.109170,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6,2017-01-11,000001.SZ,9.14,8.622291,9.17,9.13,277553.207,-0.11,0.0,-0.327154,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7,2017-01-12,000001.SZ,9.13,8.631724,9.17,9.13,391869.402,0.11,0.0,0.219058,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8,2017-01-13,000001.SZ,9.14,8.641158,9.19,9.12,397601.906,0.11,0.0,0.109290,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9,2017-01-16,000001.SZ,9.15,8.622291,9.16,9.07,623025.820,-0.22,0.0,-0.109290,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [26]:
%%time
df.ts_code=df.ts_code.str.split('.', 2).str[0]

df4=pd.merge(df,L2stocklist,how='left',on='ts_code')
#df4.drop(['index_code','level'],axis=1)

BBStock=df4[df4['ts_code'].notna()]
BBStock.fillna(0,inplace=True)
BBStock.loc[BBStock.close_qfq>=BBStock.open,'Signal']=0
BBStock.loc[BBStock.close_qfq<BBStock.open,'Signal']=1
BBStock['ChangeSignal']=BBStock.Signal.diff().abs()
BBStock.ChangeSignal.fillna(0,inplace=True) #解决首行0
BBStock['BBperiod']=BBStock.groupby('ts_code').ChangeSignal.cumsum()

#个股级别日线涨跌周期

high = BBStock.groupby(['ts_code','stock_name','BBperiod'])['high'].max().rename('high').reset_index()
low = BBStock.groupby(['ts_code','stock_name','BBperiod'])['low'].min().rename('low').reset_index()
amount = BBStock.groupby(['ts_code','stock_name','BBperiod'])['amount'].sum().rename('amount').reset_index()
open1 = BBStock.groupby(['ts_code','stock_name','BBperiod'])['open'].first().rename('open').reset_index()
close1 = BBStock.groupby(['ts_code','stock_name','BBperiod'])['close_qfq'].last().rename('close').reset_index()
lastperiod=BBStock.groupby(['ts_code','stock_name']).BBperiod.max().rename('lastbar')

BBS2 = pd.merge(open1,close1,how='left',on=('ts_code','stock_name','BBperiod')) 
BBS2 = pd.merge(BBS2,high,how='left',on=('ts_code','stock_name','BBperiod')) 
BBS2 = pd.merge(BBS2,low,how='left',on=('ts_code','stock_name','BBperiod')) 
BBS2 = pd.merge(BBS2,amount,how='left',on=('ts_code','stock_name','BBperiod')) 
BBS2 = pd.merge(BBS2,lastperiod,how='left',on=('ts_code','stock_name')) 

close=BBS2.close.values
#swsf.date=swsf.date.values

diff, dea, my_macd = talib.MACD(close,
                                             fastperiod=12,
                                             slowperiod=26,
#获取均线的数据，通过timeperiod参数来分别获取 5,10,20 日均线的数据。
                                             signalperiod=9)
BBS2['D-diff']=diff
BBS2['D-dea']=dea
BBS2['D-MACD']=my_macd
BBS2=BBS2[BBS2['BBperiod']==BBS2['lastbar']]
BBS2 = BBS2.sort_values(by=['D-MACD'],axis=0,ascending=[False])

#BBS2.to_csv('C:/Users/atianth/Desktop/BBtest2.csv',index=False,encoding='utf-8-sig') 
BBS2

Wall time: 1min 34s

,ts_code,stock_name,BBperiod,open,close,high,low,amount,lastbar,D-diff,D-dea,D-MACD
659802,688788,0,3.0,205.80,206.86,208.55,202.01,290305.564,3.0,39.486258,17.036827,22.449431
653961,688169,0,89.0,859.80,892.00,892.00,847.00,295356.905,89.0,97.513242,77.877180,19.636063
659013,688536,0,11.0,327.58,347.00,356.80,321.95,789411.368,11.0,77.301503,62.980447,14.321057
646954,605111,新洁能,5.0,129.62,149.94,149.94,128.88,1752666.541,5.0,25.984799,11.927961,14.056838
409465,300896,爱美客,14.0,551.00,535.00,560.00,512.20,1504184.343,14.0,113.859461,101.079793,12.779668
...,...,...,...,...,...,...,...,...,...,...,...,...
659442,688580,0,35.0,116.43,117.00,117.48,111.20,148461.954,35.0,-5.091787,4.832139,-9.923926
651859,688095,0,22.0,313.01,305.50,316.80,296.70,519750.991,22.0,33.995133,44.552667,-10.557535
612037,603444,吉比特,118.0,478.06,457.50,482.98,448.41,1121604.717,118.0,-31.078645,-11.798335,-19.280311
647177,605169,洪通燃气,2.0,26.18,25.88,26.51,25.50,183904.341,2.0,-20.354994,1.655495,-22.010489
409476,300897,山科智能,10.0,57.80,54.91,57.95,54.22,247110.569,10.0,-55.016508,-24.793742,-30.222767

In [27]:
%%time
BBWStock=df4[df4['ts_code'].notna()]
BBWStock.fillna(0,inplace=True)
BBWStock['year']=BBWStock.date.dt.isocalendar().year
BBWStock['week']=BBWStock.date.dt.isocalendar().week
high = BBWStock.groupby(['ts_code','stock_name','year','week'])['high'].max().rename('high').reset_index()
low = BBWStock.groupby(['ts_code','stock_name','year','week'])['low'].min().rename('low').reset_index()
amount = BBWStock.groupby(['ts_code','stock_name','year','week'])['amount'].sum().rename('amount').reset_index()
open1 = BBWStock.groupby(['ts_code','stock_name','year','week'])['open'].first().rename('open').reset_index()
close1 = BBWStock.groupby(['ts_code','stock_name','year','week'])['close_qfq'].last().rename('close').reset_index()

BBWS2 = pd.merge(open1,close1,how='left',on=('ts_code','stock_name','year','week')) 
BBWS2 = pd.merge(BBWS2,high,how='left',on=('ts_code','stock_name','year','week')) 
BBWS2 = pd.merge(BBWS2,low,how='left',on=('ts_code','stock_name','year','week')) 
BBWS2 = pd.merge(BBWS2,amount,how='left',on=('ts_code','stock_name','year','week')) 

BBWS2.loc[BBWS2.close>=BBWS2.open,'Signal']=0
BBWS2.loc[BBWS2.close<BBWS2.open,'Signal']=1
BBWS2['ChangeSignal']=BBWS2.Signal.diff().abs()
BBWS2.ChangeSignal.fillna(0,inplace=True) #解决首行0
BBWS2['BBperiod']=BBWS2.groupby(['ts_code','stock_name']).ChangeSignal.cumsum()

high2 = BBWS2.groupby(['ts_code','stock_name','BBperiod'])['high'].max().rename('high').reset_index()
low2 = BBWS2.groupby(['ts_code','stock_name','BBperiod'])['low'].min().rename('low').reset_index()
amount2 = BBWS2.groupby(['ts_code','stock_name','BBperiod'])['amount'].sum().rename('amount').reset_index()
open2 = BBWS2.groupby(['ts_code','stock_name','BBperiod'])['open'].first().rename('open').reset_index()
close2 = BBWS2.groupby(['ts_code','stock_name','BBperiod'])['close'].last().rename('close').reset_index()
lastperiod=BBWS2.groupby(['ts_code','stock_name']).BBperiod.max().rename('lastbar')

BBWS3 = pd.merge(open2,close2,how='left',on=('ts_code','stock_name','BBperiod')) 
BBWS3 = pd.merge(BBWS3,high2,how='left',on=('ts_code','stock_name','BBperiod')) 
BBWS3 = pd.merge(BBWS3,low2,how='left',on=('ts_code','stock_name','BBperiod')) 
BBWS3 = pd.merge(BBWS3,amount2,how='left',on=('ts_code','stock_name','BBperiod')) 
BBWS3 = pd.merge(BBWS3,lastperiod,how='left',on=('ts_code','stock_name')) 

close=BBWS3.close.values
#swsf.date=swsf.date.values

diff, dea, my_macd = talib.MACD(close,
                                             fastperiod=12,
                                             slowperiod=26,
#获取均线的数据，通过timeperiod参数来分别获取 5,10,20 日均线的数据。
                                             signalperiod=9)
BBWS3['W-diff']=diff
BBWS3['W-dea']=dea
BBWS3['W-MACD']=my_macd
BBWS3=BBWS3[BBWS3['BBperiod']==BBWS3['lastbar']]
BBWS3 = BBWS3.sort_values(by=['W-MACD'],axis=0,ascending=[False])

BBWS3

Wall time: 1min 20s

,ts_code,stock_name,BBperiod,open,close,high,low,amount,lastbar,W-diff,W-dea,W-MACD
105475,300896,爱美客,3.0,410.11,535.00,577.49,410.00,7594989.768,3.0,76.956303,24.653104,52.303199
172788,688536,0,4.0,253.71,347.00,356.80,245.81,2891796.881,4.0,56.108892,22.434434,33.674458
171577,688169,0,23.0,603.12,892.00,892.00,590.00,4374310.576,23.0,129.569424,101.142032,28.427392
171049,688095,0,4.0,270.00,305.50,317.60,268.56,1346527.925,4.0,60.292091,31.998654,28.293437
171665,688185,0,8.0,398.00,380.00,405.00,368.89,3163850.786,8.0,87.208226,62.144516,25.063711
...,...,...,...,...,...,...,...,...,...,...,...,...
169909,605178,时空科技,6.0,62.71,56.81,62.71,55.00,473170.400,6.0,-11.127220,9.044657,-20.171876
169903,605169,洪通燃气,2.0,27.09,25.88,28.14,24.45,1150677.945,2.0,22.105479,43.055130,-20.949652
172658,688418,0,6.0,32.11,33.75,35.00,29.78,279414.580,6.0,-30.804034,-8.370158,-22.433876
160479,603444,吉比特,38.0,466.75,457.50,482.98,445.18,2004283.899,38.0,75.966868,99.707313,-23.740446
105144,300842,帝科股份,10.0,61.00,71.21,76.08,60.89,1851444.750,10.0,-37.516409,-6.216764,-31.299645

In [28]:
%%time
BBMStock=df4[df4['ts_code'].notna()]
BBMStock.fillna(0,inplace=True)
BBMStock['year']=BBMStock.date.dt.isocalendar().year
BBMStock['month']=BBMStock.date.dt.month
high = BBMStock.groupby(['ts_code','stock_name','year','month'])['high'].max().rename('high').reset_index()
low = BBMStock.groupby(['ts_code','stock_name','year','month'])['low'].min().rename('low').reset_index()
amount = BBMStock.groupby(['ts_code','stock_name','year','month'])['amount'].sum().rename('amount').reset_index()
open1 = BBMStock.groupby(['ts_code','stock_name','year','month'])['open'].first().rename('open').reset_index()
close1 = BBMStock.groupby(['ts_code','stock_name','year','month'])['close_qfq'].last().rename('close').reset_index()

BBMS2 = pd.merge(open1,close1,how='left',on=('ts_code','stock_name','year','month')) 
BBMS2 = pd.merge(BBMS2,high,how='left',on=('ts_code','stock_name','year','month')) 
BBMS2 = pd.merge(BBMS2,low,how='left',on=('ts_code','stock_name','year','month')) 
BBMS2 = pd.merge(BBMS2,amount,how='left',on=('ts_code','stock_name','year','month')) 

BBMS2.loc[BBMS2.close>=BBMS2.open,'Signal']=0
BBMS2.loc[BBMS2.close<BBMS2.open,'Signal']=1
BBMS2['ChangeSignal']=BBMS2.Signal.diff().abs()
BBMS2.ChangeSignal.fillna(0,inplace=True) #解决首行0
BBMS2['BBperiod']=BBMS2.groupby(['ts_code','stock_name']).ChangeSignal.cumsum()

high2 = BBMS2.groupby(['ts_code','stock_name','BBperiod'])['high'].max().rename('high').reset_index()
low2 = BBMS2.groupby(['ts_code','stock_name','BBperiod'])['low'].min().rename('low').reset_index()
amount2 = BBMS2.groupby(['ts_code','stock_name','BBperiod'])['amount'].sum().rename('Mamount').reset_index()
open2 = BBMS2.groupby(['ts_code','stock_name','BBperiod'])['open'].first().rename('open').reset_index()
close2 = BBMS2.groupby(['ts_code','stock_name','BBperiod'])['close'].last().rename('close').reset_index()
lastperiod=BBMS2.groupby(['ts_code','stock_name']).BBperiod.max().rename('lastbar')

BBMS3 = pd.merge(open2,close2,how='left',on=('ts_code','stock_name','BBperiod')) 
BBMS3 = pd.merge(BBMS3,high2,how='left',on=('ts_code','stock_name','BBperiod')) 
BBMS3 = pd.merge(BBMS3,low2,how='left',on=('ts_code','stock_name','BBperiod')) 
BBMS3 = pd.merge(BBMS3,amount2,how='left',on=('ts_code','stock_name','BBperiod')) 
BBMS3 = pd.merge(BBMS3,lastperiod,how='left',on=('ts_code','stock_name')) 
BBMS3 = BBMS3.sort_values(by=['ts_code','BBperiod'],axis=0,ascending=[True,True])
BBMS3['LastMonthK']=BBMS3.close.shift(1)/BBMS3.high.shift(1)
BBMS3['CurMonthK']=BBMS3.close/BBMS3.high


close=BBMS3.close.values
#swsf.date=swsf.date.values

diff, dea, my_macd = talib.MACD(close,
                                             fastperiod=12,
                                             slowperiod=26,
#获取均线的数据，通过timeperiod参数来分别获取 5,10,20 日均线的数据。
                                             signalperiod=9)
BBMS3['M-diff']=diff
BBMS3['M-dea']=dea
BBMS3['M-MACD']=my_macd
BBMS3=BBMS3[BBMS3['BBperiod']==BBMS3['lastbar']]
BBMS3 = BBMS3.sort_values(by=['M-MACD'],axis=0,ascending=[False])

BBMS3

Wall time: 1min 7s

,ts_code,stock_name,BBperiod,open,close,high,low,Mamount,lastbar,LastMonthK,CurMonthK,M-diff,M-dea,M-MACD
32801,600519,贵州茅台,13.0,1675.00,1700.62,1732.48,1672.00,1.829519e+07,13.0,0.913578,0.981610,377.129967,244.749702,132.380265
45296,688169,0,3.0,384.40,892.00,892.00,376.00,2.339896e+07,3.0,0.908691,1.000000,113.849676,43.998202,69.851474
27041,300841,康华生物,2.0,460.00,462.39,488.60,441.10,1.839790e+06,2.0,0.463855,0.946357,90.757027,33.288811,57.468215
26779,300782,卓胜微,3.0,383.00,483.00,486.18,379.00,2.096359e+07,3.0,0.782405,0.993459,89.180084,38.111158,51.068926
2894,000661,长春高新,3.0,507.00,348.30,513.50,318.51,1.526865e+08,3.0,0.968716,0.678286,77.201652,29.598469,47.603183
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42371,603456,九洲药业,8.0,33.20,31.17,33.77,30.01,1.017144e+06,8.0,0.932402,0.923009,-21.173306,6.416839,-27.590145
26690,300761,立华股份,5.0,35.59,36.09,37.43,35.59,3.341979e+05,5.0,0.788397,0.964200,-3.652938,23.945664,-27.598602
26645,300752,隆利科技,6.0,25.90,32.75,35.00,23.53,6.635378e+06,6.0,0.860201,0.935714,-6.701735,20.987990,-27.689725
14,000001,平安银行,14.0,17.65,17.64,18.50,17.22,9.751110e+06,14.0,0.945154,0.953514,NaN,NaN,NaN
26,000002,万科A,11.0,27.66,29.46,29.57,27.66,1.129485e+07,11.0,0.963624,0.996280,NaN,NaN,NaN

In [29]:
StockReport=df4[['date','ts_code','stock_name','index_code','industry_name','close_qfq','Chg5D','Chg20D','Chg60D','Chg120D','C/S','S/M','M/L','kl1','trendscore-L']]
lastday=StockReport.date.max()
StockReport=StockReport[StockReport.date==lastday]
SDReport=BBS2[['ts_code','D-diff','D-dea','D-MACD']]
SWReport=BBWS3[['ts_code','W-diff','W-dea','W-MACD']]
SMReport=BBMS3[['ts_code','Mamount','M-diff','M-dea','M-MACD','LastMonthK','CurMonthK']]
StockReport=pd.merge(StockReport,SDReport,how='left',on=('ts_code'))
StockReport=pd.merge(StockReport,SWReport,how='left',on=('ts_code'))
StockReport=pd.merge(StockReport,SMReport,how='left',on=('ts_code'))

StockReport.to_csv('C:/quant/output/Stockoutput.csv',index=False,encoding='utf-8-sig') 
StockReport

,date,ts_code,stock_name,index_code,industry_name,close_qfq,Chg5D,Chg20D,Chg60D,Chg120D,...,D-MACD,W-diff,W-dea,W-MACD,Mamount,M-diff,M-dea,M-MACD,LastMonthK,CurMonthK
0,2020-11-06,000001,平安银行,801192,银行,17.64,0.056721,10.943396,28.759124,31.647960,...,0.117286,1.316653,0.956354,0.360299,9.751110e+06,NaN,NaN,NaN,0.945154,0.953514
1,2020-11-06,000002,万科A,801181,房地产开发,29.46,5.402504,4.062169,13.020994,17.815559,...,-0.144575,2.452855,2.690794,-0.237939,1.129485e+07,NaN,NaN,NaN,0.963624,0.996280
2,2020-11-06,000004,国农科技,801151,化学制药,26.84,4.435798,11.138716,-5.559465,-20.000000,...,0.376992,0.303413,1.008888,-0.705476,2.348425e+06,1.760472,2.005371,-0.244899,0.666378,0.963043
3,2020-11-06,000005,世纪星源,801162,环保工程及服务,2.61,2.755906,-5.090909,-11.224490,-2.611940,...,-0.008198,-0.190908,-0.226162,0.035254,8.270387e+04,-4.641004,-4.612018,-0.028986,0.821429,0.973881
4,2020-11-06,000006,深振业A,801181,房地产开发,5.83,1.039861,-18.347339,-30.179641,22.111757,...,-0.022886,0.551329,0.616861,-0.065532,2.582123e+05,-1.730970,-2.536201,0.805231,0.785714,0.976549
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4044,2020-11-06,688598,NaN,NaN,NaN,123.50,4.061341,4.351500,22.546049,0.000000,...,0.593122,18.085718,13.258218,4.827500,2.348719e+06,11.339539,2.877230,8.462308,0.915027,0.981093
4045,2020-11-06,688599,NaN,NaN,NaN,16.67,0.421687,-3.137711,1.584400,0.000000,...,0.419505,-12.432562,-12.102954,-0.329609,1.338290e+06,-6.521915,-0.673936,-5.847979,0.886971,0.960807
4046,2020-11-06,688600,NaN,NaN,NaN,20.18,5.323591,-12.979733,-28.082680,0.000000,...,-0.275524,-6.051675,-7.625309,1.573634,6.683083e+04,-8.601953,-3.390956,-5.210997,0.492857,0.980087
4047,2020-11-06,688788,NaN,NaN,NaN,206.86,7.739583,0.000000,0.000000,0.000000,...,22.449431,19.781056,0.308831,19.472225,2.124892e+06,15.800141,1.682794,14.117347,0.758567,0.967585
4048,2020-11-06,688981,NaN,NaN,NaN,64.95,3.671189,13.133600,-19.286691,0.000000,...,1.100222,7.124954,8.588610,-1.463657,5.542524e+07,10.221308,5.051621,5.169687,0.522632,0.989337