In [1]:
#coding=utf-8,
#记得改today,不要白跑啊
import tushare as ts
import pandas as pd
import talib
import time
import datetime
from opendatatools import swindex
import timestamp
from os import walk
ts.set_token('bc406c9fab768c6c699ef450685daed298c5abf2dbdba8da4e810cab')
pro = ts.pro_api()

today=20201106

In [2]:
import baostock as bs
import pandas as pd

# 登陆系统
lg = bs.login()
# 显示登陆返回信息
print('login respond error_code:'+lg.error_code)
print('login respond  error_msg:'+lg.error_msg)

# 获取指数(综合指数、规模指数、一级行业指数、二级行业指数、策略指数、成长指数、价值指数、主题指数)K线数据
# 综合指数，例如：sh.000001 上证指数，sz.399106 深证综指 等；
# 规模指数，例如：sh.000016 上证50，sh.000300 沪深300，sh.000905 中证500，sz.399001 深证成指等；
# 一级行业指数，例如：sh.000037 上证医药，sz.399433 国证交运 等；
# 二级行业指数，例如：sh.000952 300地产，sz.399951 300银行 等；
# 策略指数，例如：sh.000050 50等权，sh.000982 500等权 等；
# 成长指数，例如：sz.399376 小盘成长 等；
# 价值指数，例如：sh.000029 180价值 等；
# 主题指数，例如：sh.000015 红利指数，sh.000063 上证周期 等；

# 详细指标参数，参见“历史行情指标参数”章节
rs = bs.query_history_k_data_plus("000906.sh",
    "date,code,open,high,low,close,preclose,volume,amount,pctChg",
    start_date='2014-01-01', end_date='2020-10-31', frequency="d")
print('query_history_k_data_plus respond error_code:'+rs.error_code)
print('query_history_k_data_plus respond  error_msg:'+rs.error_msg)

# 打印结果集
data_list = []
while (rs.error_code == '0') & rs.next():
    # 获取一条记录，将记录合并在一起
    data_list.append(rs.get_row_data())
result = pd.DataFrame(data_list, columns=rs.fields)
result.to_csv("C:/quant/index/history_Index_k_data.csv", index=False)# 登出系统
bs.logout()

login success!
login respond error_code:0
login respond  error_msg:success
query_history_k_data_plus respond error_code:0
query_history_k_data_plus respond  error_msg:success
logout success!

In [3]:
#因为baostock出数据慢，手动输入当日数据后也能算MA

result=pd.read_csv("C:/quant/index/history_Index_k_data.csv")# 登出系统

ma5=talib.SMA(result.close,timeperiod=5)
ma10=talib.SMA(result.close,timeperiod=10)
ma20=talib.SMA(result.close,timeperiod=20)
ma30=talib.SMA(result.close,timeperiod=30)
ma60=talib.SMA(result.close,timeperiod=60)
ma120=talib.SMA(result.close,timeperiod=120)

ema5=talib.SMA(result.close,timeperiod=5)
ema10=talib.SMA(result.close,timeperiod=10)
ema20=talib.SMA(result.close,timeperiod=20)
ema30=talib.SMA(result.close,timeperiod=30)
ema60=talib.SMA(result.close,timeperiod=60)
ema120=talib.SMA(result.close,timeperiod=120)


result['MA5']=ma5
result['MA10']=ma10
result['MA20']=ma20
result['MA30']=ma30
result['MA60']=ma60
result['MA120']=ma120
result['EMA5']=ema5
result['EMA10']=ema10
result['EMA20']=ema20
result['EMA30']=ema30
result['EMA60']=ema60
result['EMA120']=ema120


# 结果集输出到csv文件
result.to_csv("C:/quant/index/history_Index_k_data.csv", index=False)
print(result)

# 登出系统
bs.logout()

            date       code       open       high        low      close  \
0     2014-01-02  sh.000906  2582.9100  2586.9400  2570.9500  2586.0200
1     2014-01-03  sh.000906  2576.6100  2579.2900  2544.5900  2554.8000
2     2014-01-06  sh.000906  2549.4700  2549.4700  2487.0700  2493.4000
3     2014-01-07  sh.000906  2478.0200  2504.6600  2473.2700  2496.8600
4     2014-01-08  sh.000906  2499.3500  2523.1300  2488.0000  2500.8800
...          ...        ...        ...        ...        ...        ...
1658  2020-10-26  sh.000906  4926.6937  4958.5038  4878.0131  4936.0554
1659  2020-10-27  sh.000906  4922.0691  4952.3297  4912.0689  4943.8202
1660  2020-10-28  sh.000906  4946.8813  4993.1433  4922.5219  4978.9404
1661  2020-10-29  sh.000906  4921.3398  5037.3505  4916.0026  5009.2565
1662  2020-10-30  sh.000906  5015.4587  5017.0833  4909.0489  4919.8791

       preclose       volume        amount    pctChg  ...         MA20  \
0     2589.3500   7599455200  8.043002e+10 -0.128607  ...          NaN
1     2586.0200   9460020800  9.359134e+10 -1.207259  ...          NaN
2     2554.8000  10081227200  9.306843e+10 -2.403325  ...          NaN
3     2493.4000   7096172800  7.015324e+10  0.138775  ...          NaN
4     2496.8600   8329229600  8.328050e+10  0.160993  ...          NaN
...         ...          ...           ...       ...  ...          ...
1658  4957.6898  18173623000  2.907741e+11 -0.436381  ...  4974.536495
1659  4936.0554  16824282000  2.759914e+11  0.157308  ...  4972.726250
1660  4943.8202  19559429000  3.308335e+11  0.710386  ...  4975.728945
1661  4978.9404  20970473300  3.620648e+11  0.608887  ...  4979.267785
1662  5009.2565  25192466300  4.072443e+11 -1.784245  ...  4983.309545

             MA30         MA60        MA120        EMA5       EMA10  \
0             NaN          NaN          NaN         NaN         NaN
1             NaN          NaN          NaN         NaN         NaN
2             NaN          NaN          NaN         NaN         NaN
3             NaN          NaN          NaN         NaN         NaN
4             NaN          NaN          NaN  2526.39200         NaN
...           ...          ...          ...         ...         ...
1658  4961.976417  5004.925232  4722.973984  5003.88408  5036.29994
1659  4961.152177  5006.963513  4730.337799  4981.14968  5018.83972
1660  4960.538217  5008.863230  4737.880068  4968.30780  5008.27845
1661  4964.977590  5009.250773  4745.557918  4965.15246  5002.33386
1662  4967.223687  5008.513510  4751.984507  4957.59032  4988.61076

            EMA20        EMA30        EMA60       EMA120
0             NaN          NaN          NaN          NaN
1             NaN          NaN          NaN          NaN
2             NaN          NaN          NaN          NaN
3             NaN          NaN          NaN          NaN
4             NaN          NaN          NaN          NaN
...           ...          ...          ...          ...
1658  4974.536495  4961.976417  5004.925232  4722.973984
1659  4972.726250  4961.152177  5006.963513  4730.337799
1660  4975.728945  4960.538217  5008.863230  4737.880068
1661  4979.267785  4964.977590  5009.250773  4745.557918
1662  4983.309545  4967.223687  5008.513510  4751.984507

[1663 rows x 22 columns]
logout failed!

In [4]:

pool = pro.stock_basic()
pool.head(5)
writer = pd.ExcelWriter('C:/quant/list/list.xlsx') 
pool.to_excel(writer,'Sheet1')
writer.save()
writer.close()

In [5]:

#从TUSHARE获取申万一级行业列表及其对应股票
Sdf1 = pro.index_classify(level='L1', src='SW')
Sdf1.to_csv('C:/quant/swsindex/L1.csv',index=False,encoding='utf-8-sig') 
#获取申万二级行业列表
Sdf2 = pro.index_classify(level='L2', src='SW')
Sdf2.dropna()
Sdf2['index_code']=Sdf2['index_code'].str.split('.', 2).str[0]
Sdf2.to_csv('C:/quant/swsindex/L2.csv',index=False,encoding='utf-8-sig')

#获取申万三级级行业列表
Sdf3 = pro.index_classify(level='L3', src='SW')
Sdf3.dropna()
Sdf3['index_code']=Sdf3['index_code'].str.split('.', 2).str[0]

Sdf3.to_csv('C:/quant/swsindex/L3.csv',index=False,encoding='utf-8-sig') 
#Sdf3.head(10)
#SW1=pd.merge(Sdf1,Sdf2,how='right',on=['index_code','index_code'])
#SW2=pd.merge(SW1,Sdf2,how='right',on=['index_code','index_code'])

In [6]:
%%time
#2级行业对应个股
L2stocklist=pd.DataFrame()
for i in Sdf2.index_code:
    time.sleep(0.3)
    X=str(i)
    df23, msg = swindex.get_index_cons(X)
    df23['index_code']=X
    df23.rename(columns={'stock_code':'ts_code'}, inplace = True)
    #df23=df23.drop(['start_date','weight'],axis=1)
    L2stocklist=L2stocklist.append(df23)
L2stocklist=pd.merge(L2stocklist,Sdf2,how='left',on='index_code')
L2stocklist

Wall time: 37.6 s

,ts_code,stock_name,start_date,weight,index_code,industry_name,level
0,600759,洲际油气,2015-07-01 00:00:00,9.9323,801023,石油开采,L2
1,600777,新潮能源,2017-07-03 00:00:00,27.4387,801023,石油开采,L2
2,601857,中国石油,2008-06-02 00:00:00,62.6289,801023,石油开采,L2
3,000552,靖远煤电,2008-06-02 00:00:00,1.4085,801021,煤炭开采,L2
4,000571,*ST大洲,2011-10-10 00:00:00,0.7144,801021,煤炭开采,L2
...,...,...,...,...,...,...,...
3807,600811,东方集团,2008-06-02 00:00:00,7.6193,801231,综合,L2
3808,600817,ST宏盛,2011-10-10 00:00:00,1.0086,801231,综合,L2
3809,600818,中路股份,2011-10-10 00:00:00,0.7878,801231,综合,L2
3810,603060,国检集团,2016-11-06 18:27:00,1.8584,801231,综合,L2
3811,603183,建研院,2017-08-26 09:17:00,1.1083,801231,综合,L2

In [7]:
%%time
#3级行业对应个股
L3stocklist=pd.DataFrame()
for i in Sdf3.index_code:
    time.sleep(0.3)
    X=str(i)
    df24, msg = swindex.get_index_cons(X)
    df24['index_code']=X
    df24.rename(columns={'stock_code':'ts_code'}, inplace = True)
    #df23=df23.drop(['start_date','weight'],axis=1)
    L3stocklist=L3stocklist.append(df24)
L3stocklist=pd.merge(L3stocklist,Sdf3,how='left',on='index_code')
L3stocklist

Wall time: 1min 20s

,ts_code,stock_name,start_date,weight,index_code,industry_name,level
0,600759,洲际油气,2015-07-01 00:00:00,9.9323,850211,石油开采,L3
1,600777,新潮能源,2017-07-03 00:00:00,27.4387,850211,石油开采,L3
2,601857,中国石油,2008-06-02 00:00:00,62.6289,850211,石油开采,L3
3,000552,靖远煤电,2008-06-02 00:00:00,1.8153,850221,煤炭开采,L3
4,000571,*ST大洲,2011-10-10 00:00:00,0.9208,850221,煤炭开采,L3
...,...,...,...,...,...,...,...
3855,600811,东方集团,2008-06-02 00:00:00,7.6193,852311,综合,L3
3856,600817,ST宏盛,2011-10-10 00:00:00,1.0086,852311,综合,L3
3857,600818,中路股份,2011-10-10 00:00:00,0.7878,852311,综合,L3
3858,603060,国检集团,2016-11-06 18:27:00,1.8584,852311,综合,L3
3859,603183,建研院,2017-08-26 09:17:00,1.1083,852311,综合,L3

In [8]:
L3stocklist.to_csv("C:/quant/index/L3stocklist.csv", index=False,encoding='utf-8-sig')

In [9]:
%%time
#从申银端口通过刚才过滤的2级行业列表获取数据
allindex = pd.DataFrame() 
#L3stocklist=pd.DataFrame()
for i in Sdf2.index_code:
    time.sleep(0.7)
    X=str(i)
    df2, msg = swindex.get_index_daily(X,start_date=20100101,end_date=today)
    df2.to_csv(r'C:/quant/indexdaydate/2020/'+X+'.csv',index=False,encoding='utf-8-sig') 
    df23, msg = swindex.get_index_cons(X)
    df23.rename(columns={'stock_code':'ts_code'}, inplace = True)
    df23.dropna()
    #df23=df23.drop(['start_date','weight'],axis=1)
    
    allindex = allindex.append(df2)
    #L3stocklist=L3stocklist.append(df23)
allindex = allindex.sort_values(by=['index_code','date'],axis=0,ascending=[True,True])

http://www.swsindex.com/excel2.aspx?ctable=swindexhistory&where= swindexcode in ('801023') and BargainDate >= '20100101' and BargainDate <= '20201106'
http://www.swsindex.com/excel2.aspx?ctable=swindexhistory&where= swindexcode in ('801021') and BargainDate >= '20100101' and BargainDate <= '20201106'
http://www.swsindex.com/excel2.aspx?ctable=swindexhistory&where= swindexcode in ('801022') and BargainDate >= '20100101' and BargainDate <= '20201106'
http://www.swsindex.com/excel2.aspx?ctable=swindexhistory&where= swindexcode in ('801024') and BargainDate >= '20100101' and BargainDate <= '20201106'
http://www.swsindex.com/excel2.aspx?ctable=swindexhistory&where= swindexcode in ('801035') and BargainDate >= '20100101' and BargainDate <= '20201106'
http://www.swsindex.com/excel2.aspx?ctable=swindexhistory&where= swindexcode in ('801033') and BargainDate >= '20100101' and BargainDate <= '20201106'
http://www.swsindex.com/excel2.aspx?ctable=swindexhistory&where= swindexcode in ('801034') and BargainDate >= '20100101' and BargainDate <= '20201106'
http://www.swsindex.com/excel2.aspx?ctable=swindexhistory&where= swindexcode in ('801032') and BargainDate >= '20100101' and BargainDate <= '20201106'
http://www.swsindex.com/excel2.aspx?ctable=swindexhistory&where= swindexcode in ('801036') and BargainDate >= '20100101' and BargainDate <= '20201106'
http://www.swsindex.com/excel2.aspx?ctable=swindexhistory&where= swindexcode in ('801037') and BargainDate >= '20100101' and BargainDate <= '20201106'
http://www.swsindex.com/excel2.aspx?ctable=swindexhistory&where= swindexcode in ('801041') and BargainDate >= '20100101' and BargainDate <= '20201106'
http://www.swsindex.com/excel2.aspx?ctable=swindexhistory&where= swindexcode in ('801055') and BargainDate >= '20100101' and BargainDate <= '20201106'
http://www.swsindex.com/excel2.aspx?ctable=swindexhistory&where= swindexcode in ('801053') and BargainDate >= '20100101' and BargainDate <= '20201106'
http://www.swsindex.com/excel2.aspx?ctable=swindexhistory&where= swindexcode in ('801054') and BargainDate >= '20100101' and BargainDate <= '20201106'
http://www.swsindex.com/excel2.aspx?ctable=swindexhistory&where= swindexcode in ('801051') and BargainDate >= '20100101' and BargainDate <= '20201106'
http://www.swsindex.com/excel2.aspx?ctable=swindexhistory&where= swindexcode in ('801711') and BargainDate >= '20100101' and BargainDate <= '20201106'
http://www.swsindex.com/excel2.aspx?ctable=swindexhistory&where= swindexcode in ('801712') and BargainDate >= '20100101' and BargainDate <= '20201106'
http://www.swsindex.com/excel2.aspx?ctable=swindexhistory&where= swindexcode in ('801713') and BargainDate >= '20100101' and BargainDate <= '20201106'
http://www.swsindex.com/excel2.aspx?ctable=swindexhistory&where= swindexcode in ('801721') and BargainDate >= '20100101' and BargainDate <= '20201106'
http://www.swsindex.com/excel2.aspx?ctable=swindexhistory&where= swindexcode in ('801722') and BargainDate >= '20100101' and BargainDate <= '20201106'
http://www.swsindex.com/excel2.aspx?ctable=swindexhistory&where= swindexcode in ('801725') and BargainDate >= '20100101' and BargainDate <= '20201106'
http://www.swsindex.com/excel2.aspx?ctable=swindexhistory&where= swindexcode in ('801723') and BargainDate >= '20100101' and BargainDate <= '20201106'
http://www.swsindex.com/excel2.aspx?ctable=swindexhistory&where= swindexcode in ('801724') and BargainDate >= '20100101' and BargainDate <= '20201106'
http://www.swsindex.com/excel2.aspx?ctable=swindexhistory&where= swindexcode in ('801731') and BargainDate >= '20100101' and BargainDate <= '20201106'
http://www.swsindex.com/excel2.aspx?ctable=swindexhistory&where= swindexcode in ('801732') and BargainDate >= '20100101' and BargainDate <= '20201106'
http://www.swsindex.com/excel2.aspx?ctable=swindexhistory&where= swindexcode in ('801733') and BargainDate >= '20100101' and BargainDate <= '20201106'
http://www.swsindex.com/excel2.aspx?ctable=swindexhistory&where= swindexcode in ('801734') and BargainDate >= '20100101' and BargainDate <= '20201106'
http://www.swsindex.com/excel2.aspx?ctable=swindexhistory&where= swindexcode in ('801072') and BargainDate >= '20100101' and BargainDate <= '20201106'
http://www.swsindex.com/excel2.aspx?ctable=swindexhistory&where= swindexcode in ('801074') and BargainDate >= '20100101' and BargainDate <= '20201106'
http://www.swsindex.com/excel2.aspx?ctable=swindexhistory&where= swindexcode in ('801073') and BargainDate >= '20100101' and BargainDate <= '20201106'
http://www.swsindex.com/excel2.aspx?ctable=swindexhistory&where= swindexcode in ('801075') and BargainDate >= '20100101' and BargainDate <= '20201106'
http://www.swsindex.com/excel2.aspx?ctable=swindexhistory&where= swindexcode in ('801076') and BargainDate >= '20100101' and BargainDate <= '20201106'
http://www.swsindex.com/excel2.aspx?ctable=swindexhistory&where= swindexcode in ('801741') and BargainDate >= '20100101' and BargainDate <= '20201106'
http://www.swsindex.com/excel2.aspx?ctable=swindexhistory&where= swindexcode in ('801742') and BargainDate >= '20100101' and BargainDate <= '20201106'
http://www.swsindex.com/excel2.aspx?ctable=swindexhistory&where= swindexcode in ('801743') and BargainDate >= '20100101' and BargainDate <= '20201106'
http://www.swsindex.com/excel2.aspx?ctable=swindexhistory&where= swindexcode in ('801744') and BargainDate >= '20100101' and BargainDate <= '20201106'
http://www.swsindex.com/excel2.aspx?ctable=swindexhistory&where= swindexcode in ('801094') and BargainDate >= '20100101' and BargainDate <= '20201106'
http://www.swsindex.com/excel2.aspx?ctable=swindexhistory&where= swindexcode in ('801093') and BargainDate >= '20100101' and BargainDate <= '20201106'
http://www.swsindex.com/excel2.aspx?ctable=swindexhistory&where= swindexcode in ('801092') and BargainDate >= '20100101' and BargainDate <= '20201106'
http://www.swsindex.com/excel2.aspx?ctable=swindexhistory&where= swindexcode in ('801881') and BargainDate >= '20100101' and BargainDate <= '20201106'
http://www.swsindex.com/excel2.aspx?ctable=swindexhistory&where= swindexcode in ('801111') and BargainDate >= '20100101' and BargainDate <= '20201106'
http://www.swsindex.com/excel2.aspx?ctable=swindexhistory&where= swindexcode in ('801112') and BargainDate >= '20100101' and BargainDate <= '20201106'
http://www.swsindex.com/excel2.aspx?ctable=swindexhistory&where= swindexcode in ('801131') and BargainDate >= '20100101' and BargainDate <= '20201106'
http://www.swsindex.com/excel2.aspx?ctable=swindexhistory&where= swindexcode in ('801132') and BargainDate >= '20100101' and BargainDate <= '20201106'
http://www.swsindex.com/excel2.aspx?ctable=swindexhistory&where= swindexcode in ('801143') and BargainDate >= '20100101' and BargainDate <= '20201106'
http://www.swsindex.com/excel2.aspx?ctable=swindexhistory&where= swindexcode in ('801141') and BargainDate >= '20100101' and BargainDate <= '20201106'
http://www.swsindex.com/excel2.aspx?ctable=swindexhistory&where= swindexcode in ('801142') and BargainDate >= '20100101' and BargainDate <= '20201106'
http://www.swsindex.com/excel2.aspx?ctable=swindexhistory&where= swindexcode in ('801144') and BargainDate >= '20100101' and BargainDate <= '20201106'
http://www.swsindex.com/excel2.aspx?ctable=swindexhistory&where= swindexcode in ('801203') and BargainDate >= '20100101' and BargainDate <= '20201106'
http://www.swsindex.com/excel2.aspx?ctable=swindexhistory&where= swindexcode in ('801204') and BargainDate >= '20100101' and BargainDate <= '20201106'
http://www.swsindex.com/excel2.aspx?ctable=swindexhistory&where= swindexcode in ('801205') and BargainDate >= '20100101' and BargainDate <= '20201106'
http://www.swsindex.com/excel2.aspx?ctable=swindexhistory&where= swindexcode in ('801202') and BargainDate >= '20100101' and BargainDate <= '20201106'
http://www.swsindex.com/excel2.aspx?ctable=swindexhistory&where= swindexcode in ('801016') and BargainDate >= '20100101' and BargainDate <= '20201106'
http://www.swsindex.com/excel2.aspx?ctable=swindexhistory&where= swindexcode in ('801015') and BargainDate >= '20100101' and BargainDate <= '20201106'

http://www.swsindex.com/excel2.aspx?ctable=swindexhistory&where= swindexcode in ('801011') and BargainDate >= '20100101' and BargainDate <= '20201106'
http://www.swsindex.com/excel2.aspx?ctable=swindexhistory&where= swindexcode in ('801014') and BargainDate >= '20100101' and BargainDate <= '20201106'
http://www.swsindex.com/excel2.aspx?ctable=swindexhistory&where= swindexcode in ('801012') and BargainDate >= '20100101' and BargainDate <= '20201106'
http://www.swsindex.com/excel2.aspx?ctable=swindexhistory&where= swindexcode in ('801013') and BargainDate >= '20100101' and BargainDate <= '20201106'
http://www.swsindex.com/excel2.aspx?ctable=swindexhistory&where= swindexcode in ('801017') and BargainDate >= '20100101' and BargainDate <= '20201106'
http://www.swsindex.com/excel2.aspx?ctable=swindexhistory&where= swindexcode in ('801018') and BargainDate >= '20100101' and BargainDate <= '20201106'
http://www.swsindex.com/excel2.aspx?ctable=swindexhistory&where= swindexcode in ('801123') and BargainDate >= '20100101' and BargainDate <= '20201106'
http://www.swsindex.com/excel2.aspx?ctable=swindexhistory&where= swindexcode in ('801124') and BargainDate >= '20100101' and BargainDate <= '20201106'
http://www.swsindex.com/excel2.aspx?ctable=swindexhistory&where= swindexcode in ('801212') and BargainDate >= '20100101' and BargainDate <= '20201106'
http://www.swsindex.com/excel2.aspx?ctable=swindexhistory&where= swindexcode in ('801213') and BargainDate >= '20100101' and BargainDate <= '20201106'
http://www.swsindex.com/excel2.aspx?ctable=swindexhistory&where= swindexcode in ('801214') and BargainDate >= '20100101' and BargainDate <= '20201106'
http://www.swsindex.com/excel2.aspx?ctable=swindexhistory&where= swindexcode in ('801211') and BargainDate >= '20100101' and BargainDate <= '20201106'
http://www.swsindex.com/excel2.aspx?ctable=swindexhistory&where= swindexcode in ('801215') and BargainDate >= '20100101' and BargainDate <= '20201106'
http://www.swsindex.com/excel2.aspx?ctable=swindexhistory&where= swindexcode in ('801151') and BargainDate >= '20100101' and BargainDate <= '20201106'
http://www.swsindex.com/excel2.aspx?ctable=swindexhistory&where= swindexcode in ('801155') and BargainDate >= '20100101' and BargainDate <= '20201106'
http://www.swsindex.com/excel2.aspx?ctable=swindexhistory&where= swindexcode in ('801152') and BargainDate >= '20100101' and BargainDate <= '20201106'
http://www.swsindex.com/excel2.aspx?ctable=swindexhistory&where= swindexcode in ('801154') and BargainDate >= '20100101' and BargainDate <= '20201106'
http://www.swsindex.com/excel2.aspx?ctable=swindexhistory&where= swindexcode in ('801153') and BargainDate >= '20100101' and BargainDate <= '20201106'
http://www.swsindex.com/excel2.aspx?ctable=swindexhistory&where= swindexcode in ('801156') and BargainDate >= '20100101' and BargainDate <= '20201106'
http://www.swsindex.com/excel2.aspx?ctable=swindexhistory&where= swindexcode in ('801161') and BargainDate >= '20100101' and BargainDate <= '20201106'
http://www.swsindex.com/excel2.aspx?ctable=swindexhistory&where= swindexcode in ('801164') and BargainDate >= '20100101' and BargainDate <= '20201106'
http://www.swsindex.com/excel2.aspx?ctable=swindexhistory&where= swindexcode in ('801163') and BargainDate >= '20100101' and BargainDate <= '20201106'
http://www.swsindex.com/excel2.aspx?ctable=swindexhistory&where= swindexcode in ('801162') and BargainDate >= '20100101' and BargainDate <= '20201106'
http://www.swsindex.com/excel2.aspx?ctable=swindexhistory&where= swindexcode in ('801171') and BargainDate >= '20100101' and BargainDate <= '20201106'
http://www.swsindex.com/excel2.aspx?ctable=swindexhistory&where= swindexcode in ('801175') and BargainDate >= '20100101' and BargainDate <= '20201106'
http://www.swsindex.com/excel2.aspx?ctable=swindexhistory&where= swindexcode in ('801172') and BargainDate >= '20100101' and BargainDate <= '20201106'
http://www.swsindex.com/excel2.aspx?ctable=swindexhistory&where= swindexcode in ('801173') and BargainDate >= '20100101' and BargainDate <= '20201106'
http://www.swsindex.com/excel2.aspx?ctable=swindexhistory&where= swindexcode in ('801174') and BargainDate >= '20100101' and BargainDate <= '20201106'
http://www.swsindex.com/excel2.aspx?ctable=swindexhistory&where= swindexcode in ('801176') and BargainDate >= '20100101' and BargainDate <= '20201106'
http://www.swsindex.com/excel2.aspx?ctable=swindexhistory&where= swindexcode in ('801177') and BargainDate >= '20100101' and BargainDate <= '20201106'
http://www.swsindex.com/excel2.aspx?ctable=swindexhistory&where= swindexcode in ('801178') and BargainDate >= '20100101' and BargainDate <= '20201106'
http://www.swsindex.com/excel2.aspx?ctable=swindexhistory&where= swindexcode in ('801181') and BargainDate >= '20100101' and BargainDate <= '20201106'
http://www.swsindex.com/excel2.aspx?ctable=swindexhistory&where= swindexcode in ('801182') and BargainDate >= '20100101' and BargainDate <= '20201106'
http://www.swsindex.com/excel2.aspx?ctable=swindexhistory&where= swindexcode in ('801081') and BargainDate >= '20100101' and BargainDate <= '20201106'
http://www.swsindex.com/excel2.aspx?ctable=swindexhistory&where= swindexcode in ('801083') and BargainDate >= '20100101' and BargainDate <= '20201106'
http://www.swsindex.com/excel2.aspx?ctable=swindexhistory&where= swindexcode in ('801084') and BargainDate >= '20100101' and BargainDate <= '20201106'
http://www.swsindex.com/excel2.aspx?ctable=swindexhistory&where= swindexcode in ('801082') and BargainDate >= '20100101' and BargainDate <= '20201106'
http://www.swsindex.com/excel2.aspx?ctable=swindexhistory&where= swindexcode in ('801085') and BargainDate >= '20100101' and BargainDate <= '20201106'
http://www.swsindex.com/excel2.aspx?ctable=swindexhistory&where= swindexcode in ('801101') and BargainDate >= '20100101' and BargainDate <= '20201106'
http://www.swsindex.com/excel2.aspx?ctable=swindexhistory&where= swindexcode in ('801222') and BargainDate >= '20100101' and BargainDate <= '20201106'
http://www.swsindex.com/excel2.aspx?ctable=swindexhistory&where= swindexcode in ('801761') and BargainDate >= '20100101' and BargainDate <= '20201106'
http://www.swsindex.com/excel2.aspx?ctable=swindexhistory&where= swindexcode in ('801751') and BargainDate >= '20100101' and BargainDate <= '20201106'
http://www.swsindex.com/excel2.aspx?ctable=swindexhistory&where= swindexcode in ('801752') and BargainDate >= '20100101' and BargainDate <= '20201106'
http://www.swsindex.com/excel2.aspx?ctable=swindexhistory&where= swindexcode in ('801223') and BargainDate >= '20100101' and BargainDate <= '20201106'
http://www.swsindex.com/excel2.aspx?ctable=swindexhistory&where= swindexcode in ('801102') and BargainDate >= '20100101' and BargainDate <= '20201106'
http://www.swsindex.com/excel2.aspx?ctable=swindexhistory&where= swindexcode in ('801192') and BargainDate >= '20100101' and BargainDate <= '20201106'
http://www.swsindex.com/excel2.aspx?ctable=swindexhistory&where= swindexcode in ('801193') and BargainDate >= '20100101' and BargainDate <= '20201106'
http://www.swsindex.com/excel2.aspx?ctable=swindexhistory&where= swindexcode in ('801194') and BargainDate >= '20100101' and BargainDate <= '20201106'
http://www.swsindex.com/excel2.aspx?ctable=swindexhistory&where= swindexcode in ('801191') and BargainDate >= '20100101' and BargainDate <= '20201106'
http://www.swsindex.com/excel2.aspx?ctable=swindexhistory&where= swindexcode in ('801231') and BargainDate >= '20100101' and BargainDate <= '20201106'
Wall time: 4min 53s

In [29]:
#申银源数据格式不对，转换格式
allindex['open']=allindex['open'].astype("float")
allindex['high']=allindex['high'].astype("float")
allindex['low']=allindex['low'].astype("float")
allindex['close']=allindex['close'].astype("float")
allindex['vol']=allindex['vol'].astype("float")
allindex['amount']=allindex['amount'].astype("float")
allindex['change_pct']=allindex['change_pct'].astype("float")
allindex.isnull().sum()

index_code    0
index_name    0
date          0
open          0
high          0
low           0
close         0
vol           0
amount        0
change_pct    0
dtype: int64

In [30]:
#计算申银行业指数MA，MACD
from scipy.stats import rankdata
swsf=allindex[allindex['index_code'].notna()]

close=swsf.close.values
swsf.date=swsf.date.values

diff, dea, my_macd = talib.MACD(close,
                                             fastperiod=12,
                                             slowperiod=26,
#获取均线的数据，通过timeperiod参数来分别获取 5,10,20 日均线的数据。
                                             signalperiod=9)
SMA5=talib.SMA(close,timeperiod=5)
SMA10=talib.SMA(close,timeperiod=10)
SMA20=talib.SMA(close,timeperiod=20)
SMA60=talib.SMA(close,timeperiod=60)
SMA120=talib.SMA(close,timeperiod=120)
SMA350=talib.SMA(close,timeperiod=350)

EMA5=talib.EMA(close,timeperiod=5)
EMA10=talib.EMA(close,timeperiod=10)
EMA20=talib.EMA(close,timeperiod=20)
EMA60=talib.EMA(close,timeperiod=60)
EMA120=talib.EMA(close,timeperiod=120)

swsf['diff']=diff
swsf['dea']=dea
swsf['MACD']=my_macd
swsf['SMA5']=SMA5
swsf['SMA10']=SMA10
swsf['SMA20']=SMA20
swsf['SMA60']=SMA60
swsf['SMA120']=SMA120
swsf['SMA350']=SMA350

swsf['EMA5']=EMA5
swsf['EMA10']=EMA10
swsf['EMA60']=EMA60
swsf['EMA120']=EMA120

swsf['EMA20']=EMA20
swsf['SMACD-K']=(diff-dea)/dea
swsf['C/S']=(close/SMA20-1)*100
swsf['M/L']=(SMA60/SMA120-1)*100
swsf['S/M']=(SMA20/SMA60-1)*100
swsf['BreakSignal-20D']=close/EMA20-1
swsf.reset_index(drop=True, inplace=True)

swsf['dailyamount']=swsf.groupby('date')['amount'].sum()
swsf['indexamount']=swsf.amount/swsf.dailyamount


swsf.loc[swsf['index_code'] == swsf['index_code'].shift(1),'Chg1D']= (swsf.close/swsf.close.shift(1)-1)*100
swsf.loc[swsf['index_code'] == swsf['index_code'].shift(4),'Chg5D']= (swsf.close/swsf.close.shift(4)-1)*100
swsf.loc[swsf['index_code'] == swsf['index_code'].shift(19),'Chg20D']= (swsf.close/swsf.close.shift(19)-1)*100
swsf.loc[swsf['index_code'] == swsf['index_code'].shift(59),'Chg60D']= (swsf.close/swsf.close.shift(59)-1)*100
swsf.loc[swsf['index_code'] == swsf['index_code'].shift(119),'Chg120D']= (swsf.close/swsf.close.shift(119)-1)*100

swsf.fillna(0,inplace=True) #去除null
swsf.loc[(swsf['close']>swsf['EMA20']) & (swsf['close']>swsf['SMA20']) & (swsf['SMA20']>swsf['SMA20'].shift(19)),'K1']=1 #破线拐头
swsf.loc[(swsf['EMA20']>swsf['EMA60']) & (swsf['close']>swsf['EMA20'].shift(19)),'K2']=1 #双均线交叉
swsf.loc[(swsf['EMA20']>swsf['SMA60']) & (swsf['close']>swsf['EMA20'].shift(19)),'K3']=1 
swsf.loc[(swsf['SMA20']>swsf['EMA60']) & (swsf['close']>swsf['SMA20'].shift(19)),'K4']=1 
swsf.loc[(swsf['SMA20']>swsf['SMA60']) & (swsf['close']>swsf['SMA20'].shift(19)),'K5']=1 

swsf.loc[(swsf['close']<swsf['EMA20']) & (swsf['close']<swsf['SMA20']) & (swsf['SMA20']<swsf['SMA20'].shift(19)),'K1']=-1 #空头方向破线拐头
swsf.loc[(swsf['EMA20']<swsf['EMA60']) & (swsf['close']<swsf['EMA20'].shift(19)),'K2']=-1 #双均线交叉
swsf.loc[(swsf['EMA20']<swsf['SMA60']) & (swsf['close']<swsf['EMA20'].shift(19)),'K3']=-1 
swsf.loc[(swsf['SMA20']<swsf['EMA60']) & (swsf['close']<swsf['SMA20'].shift(19)),'K4']=-1 
swsf.loc[(swsf['SMA20']<swsf['SMA60']) & (swsf['close']<swsf['SMA20'].shift(19)),'K5']=-1 
swsf.fillna(0,inplace=True) #去除null
swsf['Indextrendscore-L']=(swsf.K1+swsf.K2+swsf.K3+swsf.K4+swsf.K5)

swsf.head(10)
swsf.to_csv('C:/quant/index/SWoutput.csv',index=False,encoding='utf-8-sig')

In [44]:
BBIndex=allindex[allindex['index_code'].notna()]
BBIndex.reset_index(drop=True,inplace=True)

BBIndex.loc[BBIndex.index_code==BBIndex.index_code.shift(1) ,'pre_close']=BBIndex.close.shift(1)
BBIndex.loc[BBIndex.index_code!=BBIndex.index_code.shift(1) ,'pre_close']=BBIndex.open

BBIndex.loc[BBIndex.close>=BBIndex.pre_close,'Signal']=0
BBIndex.loc[BBIndex.close<BBIndex.pre_close,'Signal']=1
BBIndex['ChangeSignal']=BBIndex.Signal.diff().abs()
BBIndex.ChangeSignal.fillna(0,inplace=True) #解决首行0
BBIndex['BBperiod']=BBIndex.groupby('index_code').ChangeSignal.cumsum()

#板块级别日线涨跌周期

high = BBIndex.groupby(['index_code','BBperiod'])['high'].max().rename('high').reset_index()
low = BBIndex.groupby(['index_code','BBperiod'])['low'].min().rename('low').reset_index()
amount = BBIndex.groupby(['index_code','BBperiod'])['amount'].sum().rename('amount').reset_index()
pre_close1 = BBIndex.groupby(['index_code','index_name','BBperiod'])['pre_close'].first().rename('pre_close').reset_index()
close1 = BBIndex.groupby(['index_code','BBperiod'])['close'].last().rename('close').reset_index()
lastperiod=BBIndex.groupby('index_code').BBperiod.max().rename('lastbar')

BBI2 = pd.merge(pre_close1,close1,how='left',on=('index_code','BBperiod')) 
BBI2 = pd.merge(BBI2,high,how='left',on=('index_code','BBperiod')) 
BBI2 = pd.merge(BBI2,low,how='left',on=('index_code','BBperiod')) 
BBI2 = pd.merge(BBI2,amount,how='left',on=('index_code','BBperiod')) 
BBI2 = pd.merge(BBI2,lastperiod,how='left',on='index_code') 

close=BBI2.close.values
#swsf.date=swsf.date.values

diff, dea, my_macd = talib.MACD(close,
                                             fastperiod=12,
                                             slowperiod=26,
#获取均线的数据，通过timeperiod参数来分别获取 5,10,20 日均线的数据。
                                             signalperiod=9)
BBI2['D-diff']=diff
BBI2['D-dea']=dea
BBI2['D-MACD']=my_macd

BBI2.to_csv('C:/quant/index/SWBBoutput-D.csv',index=False,encoding='utf-8-sig')

BBI2=BBI2[BBI2['BBperiod']==BBI2['lastbar']]
BBI2 = BBI2.sort_values(by=['D-MACD'],axis=0,ascending=[False])

 
BBI2

,index_code,index_name,BBperiod,pre_close,close,high,low,amount,lastbar,D-diff,D-dea,D-MACD
45202,801111,白色家电,1319.0,20889.55,22607.00,22890.47,20795.76,641.54,1319.0,772.120846,502.627393,269.493454
99424,801712,玻璃制造,810.0,8600.19,9197.21,9532.45,8459.39,150.25,810.0,531.292605,397.479913,133.812692
41306,801094,汽车整车,1301.0,7256.11,8112.31,8495.97,7195.75,810.39,1301.0,556.201202,427.675078,128.526124
61850,801156,医疗服务,1278.0,11472.94,11249.44,11626.39,10983.85,211.89,1278.0,460.805784,347.446790,113.358994
47880,801123,饮料制造,1328.0,33549.79,33274.11,33730.31,32823.40,254.00,1328.0,1032.144972,950.982414,81.162559
...,...,...,...,...,...,...,...,...,...,...,...,...
56705,801152,生物制品,1296.0,15106.81,14425.49,15410.22,14132.39,346.38,1296.0,-236.274746,-127.099054,-109.175692
108335,801741,航天装备,836.0,11677.76,11446.99,11786.56,11341.75,49.15,836.0,8.340708,144.132438,-135.791730
93872,801214,旅游综合,1299.0,13046.56,12702.41,13330.28,12487.86,58.77,1299.0,-136.775077,5.005980,-141.781057
109949,801743,地面兵装,810.0,15208.16,15021.99,15399.88,14848.48,25.31,810.0,-101.522394,59.181430,-160.703824
83608,801193,券商,710.0,6106.96,5950.38,6134.78,5896.73,213.76,710.0,-1448.053571,-1014.686205,-433.367366

In [46]:
BBIndex=allindex[allindex['index_code'].notna()]
BBIndex.reset_index(drop=True,inplace=True)

BBIndex.loc[BBIndex.index_code==BBIndex.index_code.shift(1) ,'pre_close']=BBIndex.close.shift(1)
BBIndex.loc[BBIndex.index_code!=BBIndex.index_code.shift(1) ,'pre_close']=BBIndex.open
BBIndex.loc[BBIndex.close>=BBIndex.pre_close,'Signal']=0
BBIndex.loc[BBIndex.close<BBIndex.pre_close,'Signal']=1
BBIndex['ChangeSignal']=BBIndex.Signal.diff().abs()
BBIndex.ChangeSignal.fillna(0,inplace=True) #解决首行0
BBIndex['BBperiod']=BBIndex.groupby('index_code').ChangeSignal.cumsum()

#板块级别日线涨跌周期

high = BBIndex.groupby(['index_code','BBperiod'])['high'].max().rename('high').reset_index()
low = BBIndex.groupby(['index_code','BBperiod'])['low'].min().rename('low').reset_index()
amount = BBIndex.groupby(['index_code','BBperiod'])['amount'].sum().rename('amount').reset_index()
pre_close1 = BBIndex.groupby(['index_code','index_name','BBperiod'])['pre_close'].first().rename('pre_close').reset_index()
close1 = BBIndex.groupby(['index_code','BBperiod'])['close'].last().rename('close').reset_index()
lastperiod=BBIndex.groupby('index_code').BBperiod.max().rename('lastbar')

BBI2 = pd.merge(pre_close1,close1,how='left',on=('index_code','BBperiod')) 
BBI2 = pd.merge(BBI2,high,how='left',on=('index_code','BBperiod')) 
BBI2 = pd.merge(BBI2,low,how='left',on=('index_code','BBperiod')) 
BBI2 = pd.merge(BBI2,amount,how='left',on=('index_code','BBperiod')) 
BBI2 = pd.merge(BBI2,lastperiod,how='left',on='index_code') 

close=BBI2.close.values
#swsf.date=swsf.date.values

diff, dea, my_macd = talib.MACD(close,
                                             fastperiod=12,
                                             slowperiod=26,
#获取均线的数据，通过timeperiod参数来分别获取 5,10,20 日均线的数据。
                                             signalperiod=9)
BBI2['D-diff']=diff
BBI2['D-dea']=dea
BBI2['D-MACD']=my_macd

BBI2.to_csv('C:/quant/index/SWBBoutput-D.csv',index=False,encoding='utf-8-sig')

BBI2=BBI2[BBI2['BBperiod']==BBI2['lastbar']]
BBI2 = BBI2.sort_values(by=['D-MACD'],axis=0,ascending=[False])

 
BBI2

,index_code,index_name,BBperiod,pre_close,close,high,low,amount,lastbar,D-diff,D-dea,D-MACD
45202,801111,白色家电,1319.0,20889.55,22607.00,22890.47,20795.76,641.54,1319.0,772.120846,502.627393,269.493454
99424,801712,玻璃制造,810.0,8600.19,9197.21,9532.45,8459.39,150.25,810.0,531.292605,397.479913,133.812692
41306,801094,汽车整车,1301.0,7256.11,8112.31,8495.97,7195.75,810.39,1301.0,556.201202,427.675078,128.526124
61850,801156,医疗服务,1278.0,11472.94,11249.44,11626.39,10983.85,211.89,1278.0,460.805784,347.446790,113.358994
47880,801123,饮料制造,1328.0,33549.79,33274.11,33730.31,32823.40,254.00,1328.0,1032.144972,950.982414,81.162559
...,...,...,...,...,...,...,...,...,...,...,...,...
56705,801152,生物制品,1296.0,15106.81,14425.49,15410.22,14132.39,346.38,1296.0,-236.274746,-127.099054,-109.175692
108335,801741,航天装备,836.0,11677.76,11446.99,11786.56,11341.75,49.15,836.0,8.340708,144.132438,-135.791730
93872,801214,旅游综合,1299.0,13046.56,12702.41,13330.28,12487.86,58.77,1299.0,-136.775077,5.005980,-141.781057
109949,801743,地面兵装,810.0,15208.16,15021.99,15399.88,14848.48,25.31,810.0,-101.522394,59.181430,-160.703824
83608,801193,券商,710.0,6106.96,5950.38,6134.78,5896.73,213.76,710.0,-1448.053571,-1014.686205,-433.367366

In [47]:
BBWIndex=allindex[allindex['index_code'].notna()]
BBWIndex.reset_index(drop=True,inplace=True)

BBWIndex.loc[BBIndex.index_code==BBIndex.index_code.shift(1) ,'pre_close']=BBIndex.close.shift(1)
BBWIndex.loc[BBIndex.index_code!=BBIndex.index_code.shift(1) ,'pre_close']=BBIndex.pre_close
BBWIndex['year']=BBWIndex.date.dt.isocalendar().year
BBWIndex['week']=BBWIndex.date.dt.isocalendar().week
high = BBWIndex.groupby(['index_code','year','week'])['high'].max().rename('high').reset_index()
low = BBWIndex.groupby(['index_code','year','week'])['low'].min().rename('low').reset_index()
amount = BBWIndex.groupby(['index_code','year','week'])['amount'].sum().rename('amount').reset_index()
pre_close1 = BBWIndex.groupby(['index_code','index_name','year','week'])['pre_close'].first().rename('pre_close').reset_index()
close1 = BBWIndex.groupby(['index_code','year','week'])['close'].last().rename('close').reset_index()

BBWI2 = pd.merge(pre_close1,close1,how='left',on=('index_code','year','week')) 
BBWI2 = pd.merge(BBWI2,high,how='left',on=('index_code','year','week')) 
BBWI2 = pd.merge(BBWI2,low,how='left',on=('index_code','year','week')) 
BBWI2 = pd.merge(BBWI2,amount,how='left',on=('index_code','year','week')) 

BBWI2.loc[BBWI2.close>=BBWI2.pre_close,'Signal']=0
BBWI2.loc[BBWI2.close<BBWI2.pre_close,'Signal']=1
BBWI2['ChangeSignal']=BBWI2.Signal.diff().abs()
BBWI2.ChangeSignal.fillna(0,inplace=True) #解决首行0
BBWI2['BBperiod']=BBWI2.groupby('index_code').ChangeSignal.cumsum()

high2 = BBWI2.groupby(['index_code','BBperiod'])['high'].max().rename('high').reset_index()
low2 = BBWI2.groupby(['index_code','BBperiod'])['low'].min().rename('low').reset_index()
amount2 = BBWI2.groupby(['index_code','BBperiod'])['amount'].sum().rename('amount').reset_index()
pre_close2 = BBWI2.groupby(['index_code','index_name','BBperiod'])['pre_close'].first().rename('pre_close').reset_index()
close2 = BBWI2.groupby(['index_code','BBperiod'])['close'].last().rename('close').reset_index()
lastperiod=BBWI2.groupby('index_code').BBperiod.max().rename('lastbar')

BBWI3 = pd.merge(pre_close2,close2,how='left',on=('index_code','BBperiod')) 
BBWI3 = pd.merge(BBWI3,high2,how='left',on=('index_code','BBperiod')) 
BBWI3 = pd.merge(BBWI3,low2,how='left',on=('index_code','BBperiod')) 
BBWI3 = pd.merge(BBWI3,amount2,how='left',on=('index_code','BBperiod')) 
BBWI3 = pd.merge(BBWI3,lastperiod,how='left',on='index_code') 

close=BBWI3.close.values
#swsf.date=swsf.date.values

diff, dea, my_macd = talib.MACD(close,
                                             fastperiod=12,
                                             slowperiod=26,
#获取均线的数据，通过timeperiod参数来分别获取 5,10,20 日均线的数据。
                                             signalperiod=9)
BBWI3['W-diff']=diff
BBWI3['W-dea']=dea
BBWI3['W-MACD']=my_macd

BBWI3.to_csv('C:/quant/index/SWBBoutput-W.csv',index=False,encoding='utf-8-sig')
BBWI3=BBWI3[BBWI3['BBperiod']==BBWI3['lastbar']]
BBWI3 = BBWI3.sort_values(by=['W-MACD'],axis=0,ascending=[False])

BBWI3

,index_code,index_name,BBperiod,pre_close,close,high,low,amount,lastbar,W-diff,W-dea,W-MACD
10216,801123,饮料制造,278.0,29607.86,33274.11,33831.52,29579.15,5273.26,278.0,3605.055732,2684.292505,920.763227
9652,801111,白色家电,284.0,18320.74,22607.00,22890.47,18089.51,3097.40,284.0,1230.065079,896.754474,333.310605
21198,801712,玻璃制造,162.0,7519.43,9197.21,9532.45,7391.02,301.71,162.0,938.402398,613.353071,325.049327
22755,801733,电源设备,156.0,12473.20,13537.19,14227.82,12131.82,3918.73,156.0,1563.342853,1241.974944,321.367909
8825,801094,汽车整车,280.0,5561.49,8112.31,8495.97,5478.16,3550.38,280.0,487.326734,174.641411,312.685323
...,...,...,...,...,...,...,...,...,...,...,...,...
19458,801212,景点,280.0,9146.71,9255.86,9381.20,8849.84,23.91,280.0,288.650757,380.723076,-92.072318
1933,801017,畜禽养殖,237.0,4182.43,3910.12,4257.89,3838.22,451.49,237.0,-17.199616,82.632945,-99.832561
2157,801018,动物保健,224.0,8791.66,7803.14,8990.06,7612.43,181.02,224.0,621.213102,726.620458,-105.407355
21036,801711,水泥制造,168.0,8174.60,8655.82,8755.47,8068.67,255.87,168.0,428.685601,580.453899,-151.768298
17802,801193,券商,155.0,6106.96,5950.38,6134.78,5896.73,213.76,155.0,97.273578,817.212814,-719.939236

In [48]:
BBMIndex=allindex[allindex['index_code'].notna()]
BBMIndex.reset_index(drop=True,inplace=True)

BBMIndex.loc[BBIndex.index_code==BBIndex.index_code.shift(1) ,'pre_close']=BBIndex.close.shift(1)
BBMIndex.loc[BBIndex.index_code!=BBIndex.index_code.shift(1) ,'pre_close']=BBIndex.pre_close
BBMIndex['year']=BBMIndex.date.dt.isocalendar().year
BBMIndex['month']=BBMIndex.date.dt.month
high = BBMIndex.groupby(['index_code','year','month'])['high'].max().rename('high').reset_index()
low = BBMIndex.groupby(['index_code','year','month'])['low'].min().rename('low').reset_index()
amount = BBMIndex.groupby(['index_code','year','month'])['amount'].sum().rename('amount').reset_index()
pre_close1 = BBMIndex.groupby(['index_code','index_name','year','month'])['pre_close'].first().rename('pre_close').reset_index()
close1 = BBMIndex.groupby(['index_code','year','month'])['close'].last().rename('close').reset_index()

BBMI2 = pd.merge(pre_close1,close1,how='left',on=('index_code','year','month')) 
BBMI2 = pd.merge(BBMI2,high,how='left',on=('index_code','year','month')) 
BBMI2 = pd.merge(BBMI2,low,how='left',on=('index_code','year','month')) 
BBMI2 = pd.merge(BBMI2,amount,how='left',on=('index_code','year','month')) 

BBMI2.loc[BBMI2.close>=BBMI2.pre_close,'Signal']=0
BBMI2.loc[BBMI2.close<BBMI2.pre_close,'Signal']=1
BBMI2['ChangeSignal']=BBMI2.Signal.diff().abs()
BBMI2.ChangeSignal.fillna(0,inplace=True) #解决首行0
BBMI2['BBperiod']=BBMI2.groupby('index_code').ChangeSignal.cumsum()

high2 = BBMI2.groupby(['index_code','BBperiod'])['high'].max().rename('high').reset_index()
low2 = BBMI2.groupby(['index_code','BBperiod'])['low'].min().rename('low').reset_index()
amount2 = BBMI2.groupby(['index_code','BBperiod'])['amount'].sum().rename('amount').reset_index()
pre_close2 = BBMI2.groupby(['index_code','index_name','BBperiod'])['pre_close'].first().rename('pre_close').reset_index()
close2 = BBMI2.groupby(['index_code','BBperiod'])['close'].last().rename('close').reset_index()
lastperiod=BBMI2.groupby('index_code').BBperiod.max().rename('lastbar')

BBMI3 = pd.merge(pre_close2,close2,how='left',on=('index_code','BBperiod')) 
BBMI3 = pd.merge(BBMI3,high2,how='left',on=('index_code','BBperiod')) 
BBMI3 = pd.merge(BBMI3,low2,how='left',on=('index_code','BBperiod')) 
BBMI3 = pd.merge(BBMI3,amount2,how='left',on=('index_code','BBperiod')) 
BBMI3 = pd.merge(BBMI3,lastperiod,how='left',on='index_code') 

close=BBMI3.close.values
#swsf.date=swsf.date.values

diff, dea, my_macd = talib.MACD(close,
                                             fastperiod=12,
                                             slowperiod=26,
#获取均线的数据，通过timeperiod参数来分别获取 5,10,20 日均线的数据。
                                             signalperiod=9)
BBMI3['M-diff']=diff
BBMI3['M-dea']=dea
BBMI3['M-MACD']=my_macd

BBMI3.to_csv('C:/quant/index/SWBBoutput-M.csv',index=False,encoding='utf-8-sig')

BBMI3=BBMI3[BBMI3['BBperiod']==BBMI3['lastbar']]
BBMI3 = BBMI3.sort_values(by=['M-MACD'],axis=0,ascending=[False])

BBMI3

,index_code,index_name,BBperiod,pre_close,close,high,low,amount,lastbar,M-diff,M-dea,M-MACD
2218,801123,饮料制造,58.0,30136.31,20689.49,33831.52,20175.40,5157.88,58.0,4231.652195,3696.317086,535.335109
4487,801214,旅游综合,65.0,6580.76,6641.09,6661.76,6526.73,23.09,65.0,1708.078592,1362.122882,345.955710
2646,801152,生物制品,64.0,8554.76,8761.44,8888.95,8385.74,134.52,64.0,1695.340005,1371.075799,324.264206
2912,801156,医疗服务,70.0,6492.34,6605.38,6685.02,6376.75,75.53,70.0,1334.160570,1023.712020,310.448550
2710,801153,医疗器械,64.0,5673.41,5842.01,5893.72,5584.99,115.54,64.0,906.355818,598.146800,308.209018
...,...,...,...,...,...,...,...,...,...,...,...,...
1932,801094,汽车整车,62.0,4134.65,4422.64,8495.97,3996.81,10769.63,62.0,-245.283405,-165.456151,-79.827254
4191,801204,专业零售,40.0,8838.47,7966.11,9881.35,7777.85,386.27,40.0,-217.562497,-120.899090,-96.663407
4866,801722,装修装饰,40.0,6064.49,6161.86,6455.93,5973.27,99.26,40.0,-804.688593,-702.351382,-102.337211
3449,801174,机场,68.0,7161.80,8789.44,8846.64,6717.95,84.19,68.0,863.434194,996.309816,-132.875622
4980,801725,园林工程,34.0,5526.88,5516.57,5800.29,5363.72,88.81,34.0,-969.491566,-701.310795,-268.180771

In [49]:
IndexReport=swsf[['date','index_code','index_name','close','Chg1D','Chg5D','Chg20D','Chg60D','Chg120D','C/S','S/M','M/L','K1','Indextrendscore-L']]
lastday=IndexReport.date.max()
IndexReport=IndexReport[IndexReport.date==lastday]
IDReport=BBI2[['index_code','D-diff','D-dea','D-MACD']]
IWReport=BBWI3[['index_code','W-diff','W-dea','W-MACD']]
IMReport=BBMI3[['index_code','M-diff','M-dea','M-MACD']]
IndexReport=pd.merge(IndexReport,IDReport,how='left',on='index_code')
IndexReport=pd.merge(IndexReport,IWReport,how='left',on='index_code')
IndexReport=pd.merge(IndexReport,IMReport,how='left',on='index_code')

IndexReport.to_csv('C:/quant/output/Indexoutput.csv',index=False,encoding='utf-8-sig') 
IndexReport

,date,index_code,index_name,close,Chg1D,Chg5D,Chg20D,Chg60D,Chg120D,C/S,...,Indextrendscore-L,D-diff,D-dea,D-MACD,W-diff,W-dea,W-MACD,M-diff,M-dea,M-MACD
0,2020-11-06,801011,林业,1042.10,0.109514,2.012648,-10.772234,-24.908847,14.842080,-2.849717,...,-5.0,-49.665524,-34.770680,-14.894844,-26.390036,-30.329671,3.939634,-200.467331,-177.161579,-23.305752
1,2020-11-06,801012,农产品加工,2695.51,0.724180,3.911659,-6.639305,-13.429255,19.643047,-0.989313,...,-5.0,-38.641608,-2.689513,-35.952095,207.348037,207.341461,0.006576,-0.820443,-44.153211,43.332768
2,2020-11-06,801013,农业综合,2032.70,-4.230409,0.532659,-1.221669,19.409035,18.410169,-2.907775,...,-1.0,16.732281,28.422255,-11.689974,49.594616,-1.396741,50.991356,-150.185902,-150.568600,0.382699
3,2020-11-06,801014,饲料,7629.49,-2.350527,-0.963818,-7.099622,-21.167644,-0.395572,-3.654242,...,-5.0,-199.287088,-182.094872,-17.192216,600.401430,659.388423,-58.986993,1072.244042,900.212543,172.031499
4,2020-11-06,801015,渔业,759.32,-1.491918,2.588629,-11.695682,-17.537820,2.716303,-5.529190,...,-5.0,-31.317595,-20.332879,-10.984716,-4.280176,-3.649106,-0.631070,-232.676167,-242.225732,9.549565
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
93,2020-11-06,801744,船舶制造,2275.74,-0.814149,3.662303,-7.590167,-14.697923,15.017689,-2.762381,...,-5.0,-45.342377,-28.866123,-16.476254,47.683908,40.239030,7.444878,-686.744273,-952.999724,266.255451
94,2020-11-06,801751,营销传播,4024.79,0.109193,3.539566,8.611961,27.049149,38.188317,2.624533,...,5.0,140.350825,143.157084,-2.806259,235.487438,139.554571,95.932867,-501.239963,-597.315063,96.075100
95,2020-11-06,801752,互联网传媒,1267.73,-0.908274,1.484162,-10.446380,-15.852671,9.338911,-3.893010,...,-5.0,-45.784867,-33.100319,-12.684548,77.006571,98.831298,-21.824726,-180.096946,-266.696159,86.599213
96,2020-11-06,801761,文化传媒,1832.97,-0.601929,1.872982,-5.919037,-7.691959,6.361484,-2.087446,...,-5.0,-38.336232,-21.931061,-16.405171,12.533147,13.260476,-0.727329,-359.040928,-298.896691,-60.144237
97,2020-11-06,801881,其他交运设备,2191.50,-2.089998,2.817331,13.552165,27.257418,87.642883,5.083419,...,5.0,118.252682,117.585116,0.667566,205.915361,123.676438,82.238923,-95.951380,-152.335353,56.383973

In [50]:

#从TUSHARE端口获取成分股
ISindex = pd.DataFrame() 

for i in Sdf1.index_code:
    time.sleep(0.7)
    Tf=pro.index_member(index_code=i)    
    ISindex = ISindex.append(Tf)

ISindex.to_csv(r'C:/quant/swsindex/total.csv') 
ISindex.rename(columns={'con_code':'ts_code'}, inplace = True)
ISindex=pd.merge(ISindex,Sdf2,how='left',on='index_code')
ISindex=ISindex.drop(["in_date",'out_date','level'],axis=1)

ISindex

     index_code    ts_code industry_name
0     801020.SI  600348.SH           NaN
1     801020.SI  600121.SH           NaN
2     801020.SI  600157.SH           NaN
3     801020.SI  600792.SH           NaN
4     801020.SI  600123.SH           NaN
...         ...        ...           ...
3730  801230.SI  600175.SH           NaN
3731  801230.SI  600149.SH           NaN
3732  801230.SI  600234.SH           NaN
3733  801230.SI  300688.SZ           NaN
3734  801230.SI  603183.SH           NaN

[3735 rows x 3 columns]

In [51]:

#从TUSHARE端口获取成分股
ISindex3 = pd.DataFrame() 

#for i in Sdf3.index_code:
 #   time.sleep(0.7)
Tf=pro.index_member(index_code='850553')    
   # ISindex3 = ISindex3.append(Tf)

#ISindex3.rename(columns={'con_code':'ts_code'}, inplace = True)
#ISindex3=pd.merge(ISindex3,Sdf3,how='left',on='index_code')
#ISindex3=ISindex3.drop(["in_date",'out_date','level'],axis=1)
#ISindex3.to_csv(r'C:/quant/swsindex/L3.csv') 

Tf

Empty DataFrame
Columns: [index_code, con_code, in_date, out_date]
Index: []

In [52]:
latestday=max(swsf.date)
ETF=swsf[swsf.date==latestday]
ETF=ETF[['index_code','K1','Indextrendscore-L']]
ISindex['index_code']=ISindex['index_code'].str.split('.', 2).str[0]

ISindex2 = pd.merge(ISindex, ETF, how='left',on='index_code') #分段信息
ISindex2

     index_code    ts_code industry_name  K1  Indextrendscore-L
0        801020  600348.SH           NaN NaN                NaN
1        801020  600121.SH           NaN NaN                NaN
2        801020  600157.SH           NaN NaN                NaN
3        801020  600792.SH           NaN NaN                NaN
4        801020  600123.SH           NaN NaN                NaN
...         ...        ...           ...  ..                ...
3730     801230  600175.SH           NaN NaN                NaN
3731     801230  600149.SH           NaN NaN                NaN
3732     801230  600234.SH           NaN NaN                NaN
3733     801230  300688.SZ           NaN NaN                NaN
3734     801230  603183.SH           NaN NaN                NaN

[3735 rows x 5 columns]

In [53]:
#tushare交易日历
calendar = pro.query('trade_cal', start_date='20201105', end_date=today)
calendar = calendar.drop(calendar[calendar['is_open']==0].index)
calendar

  exchange  cal_date  is_open
0      SSE  20201105        1
1      SSE  20201106        1

In [54]:

#从tushare下载日数据

for i in calendar.cal_date:  #range(20201021,today+1):
    time.sleep(0.75)
    print (i) 
    x=str(i)
    df = pro.daily(trade_date=x) #个股数据
    Adf = pro.query('adj_factor', trade_date=x) #复权因子
    Adf.rename(columns={'trade_date':'trade_date_x'}, inplace = True)
    Adf.adj_factor.fillna(0,inplace=True)


    Mdf = pro.moneyflow(trade_date=x) #个股资金流向，出韭菜指数
    X1=pd.merge(df,Mdf,on='ts_code')
    X1=pd.merge(X1,Adf,on=['ts_code','trade_date_x'])

    mf = pro.margin(trade_date=x)#融资融券数据
    GCdf = pro.repo_daily(ts_code='204001.sh',trade_date=x) # 逆回购数据
    #HSdf = pro.repo_daily(ts_code='000906.sh',trade_date=x) # 逆回购数据

    #X2=pd.merge(mf,GCdf,on='trade_date')

    #df2 = pro.index_dailybasic(start_date=x,fields='ts_code,trade_date,turnover_rate,pe,pe_ttm')
    #pe = df2['pe_ttm']


    writer1 = X1.to_csv('C:/quant/daydate/recentdecade/'+x + '.csv') 
    writer2 = GCdf.to_csv('C:/quant/GCdata/2020/'+x + '.csv') 
    writer3 = mf.to_csv('C:/quant/financing/2020/'+x + '.csv') #要晚一天出，所以不能合并
    #writer4 = HSdf.to_csv('C:/quant/index/2020/'+x + '.csv') #要晚一天出，所以不能合并


   # df.to_csv(writer)
  #  writer.save()
   # writer.close()

20201105
20201106

In [55]:
'''#生成15-20年单年数据
import pandas as pd
import datetime
import numpy as np
from os import walk
for root,dirs,files in walk(r'C:/quant/daydate/2020/',topdown=False):
    num = len(files)
    alldata = pd.DataFrame() 
for i in range(num):
    newdata = pd.read_csv(r'C:/quant/daydate/2020/%s'%files[i])
    
    alldata = alldata.append(newdata)
alldata = alldata.sort_values(by=['ts_code','trade_date_x'],axis=0,ascending=[True,True])
alldata.reset_index(drop=True, inplace=True)
alldata.to_csv('C:/quant/daydate/summary/2020summary.csv') 
'''

"#生成15-20年单年数据\nimport pandas as pd\nimport datetime\nimport numpy as np\nfrom os import walk\nfor root,dirs,files in walk(r'C:/quant/daydate/2020/',topdown=False):\n    num = len(files)\n    alldata = pd.DataFrame() \nfor i in range(num):\n    newdata = pd.read_csv(r'C:/quant/daydate/2020/%s'%files[i])\n    \n    alldata = alldata.append(newdata)\nalldata = alldata.sort_values(by=['ts_code','trade_date_x'],axis=0,ascending=[True,True])\nalldata.reset_index(drop=True, inplace=True)\nalldata.to_csv('C:/quant/daydate/summary/2020summary.csv') \n"

In [56]:

%%time
#生成totalsummary原始版

for root,dirs,files in walk(r'C:/quant/daydate/recentdecade',topdown=False):
    num = len(files)
    Salldata = pd.DataFrame()

for i in range(num):
    newdata = pd.read_csv(r'C:/quant/daydate/recentdecade/%s'%files[i])
    newdata = newdata.drop(newdata.columns[0],axis=1) #去除tushare源生数据首列index

    Salldata = Salldata.append(newdata)
Salldata = Salldata.sort_values(by=['ts_code','trade_date_x'],axis=0,ascending=[True,True])
Salldata.reset_index(drop=True, inplace=True)
Salldata.drop_duplicates()
Salldata.to_csv('C:/quant/daydate/summary/totalsummary.csv') 
Salldata

Wall time: 16min 45s

,ts_code,trade_date_x,open,high,low,close,pre_close,change,pct_chg,vol,...,buy_lg_amount,sell_lg_vol,sell_lg_amount,buy_elg_vol,buy_elg_amount,sell_elg_vol,sell_elg_amount,net_mf_vol,net_mf_amount,adj_factor
0,000001.SZ,20170103,9.11,9.18,9.09,9.16,9.10,0.06,0.6600,459840.49,...,12849.44,142781,13065.97,113061,10343.41,130706,11939.93,71350,6531.67,104.758
1,000001.SZ,20170104,9.15,9.18,9.14,9.16,9.16,0.00,0.0000,449329.53,...,11503.47,128951,11810.56,104137,9540.33,176725,16185.19,-6884,-608.63,104.758
2,000001.SZ,20170105,9.17,9.18,9.15,9.17,9.16,0.01,0.1100,344372.91,...,8720.31,111251,10200.48,59032,5413.23,66840,6128.81,17325,1604.98,104.758
3,000001.SZ,20170106,9.17,9.17,9.11,9.13,9.17,-0.04,-0.4400,358154.20,...,8301.36,96851,8851.30,94131,8599.49,75682,6910.19,-137025,-12502.51,104.758
4,000001.SZ,20170109,9.13,9.17,9.11,9.15,9.13,0.02,0.2200,361081.57,...,6681.79,102405,9358.58,116900,10686.08,96489,8817.27,-38202,-3471.15,104.758
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2345247,688981.SH,20201102,63.44,63.47,60.35,62.65,62.24,0.41,0.6587,511623.09,...,120185.20,171303,106345.67,89140,55622.43,126488,78428.69,-20038,-11856.99,1.000
2345248,688981.SH,20201103,62.50,65.47,62.34,64.56,62.65,1.91,3.0487,550197.05,...,147040.39,199883,129034.01,99171,64108.08,101480,65476.69,51522,33595.56,1.000
2345249,688981.SH,20201104,64.20,65.25,62.51,63.00,64.56,-1.56,-2.4164,460192.42,...,72350.27,136837,87150.87,57213,36530.15,91734,58296.44,-42276,-26532.14,1.000
2345250,688981.SH,20201105,65.00,65.50,63.56,64.84,63.00,1.84,2.9206,414596.41,...,98726.41,144104,93106.71,101078,65479.96,73173,47270.95,49461,32197.90,1.000
2345251,688981.SH,20201106,64.59,65.65,64.02,64.95,64.84,0.11,0.1696,358663.55,...,83456.40,122543,79412.41,67930,44083.48,89107,57705.37,16287,10816.59,1.000

In [57]:
'''%%time
for root,dirs,files in walk(r'C:/quant/daydate/temp',topdown=False):
    num = len(files)
    alldata = pd.read_csv(r'C:/quant/daydate/summary/totalsummary.csv')

for i in range(num):
    newdata = pd.read_csv(r'C:/quant/daydate/temp/%s'%files[i])
    newdata = newdata.drop(newdata.columns[0],axis=1) #去除tushare源生数据首列index
    newdata=newdata.dropna(subset=["trade_date_x"])
    alldata = alldata.append(newdata)
alldata = alldata.dropna(subset=['trade_date_x'])
alldata = alldata.sort_values(by=['ts_code','trade_date_x'],axis=0,ascending=[True,True])
alldata.reset_index(drop=True, inplace=True)
alldata.to_csv('C:/quant/daydate/summary/totalsummary.csv') 
alldata'''

'%%time\nfor root,dirs,files in walk(r\'C:/quant/daydate/temp\',topdown=False):\n    num = len(files)\n    alldata = pd.read_csv(r\'C:/quant/daydate/summary/totalsummary.csv\')\n\nfor i in range(num):\n    newdata = pd.read_csv(r\'C:/quant/daydate/temp/%s\'%files[i])\n    newdata = newdata.drop(newdata.columns[0],axis=1) #去除tushare源生数据首列index\n    newdata=newdata.dropna(subset=["trade_date_x"])\n    alldata = alldata.append(newdata)\nalldata = alldata.dropna(subset=[\'trade_date_x\'])\nalldata = alldata.sort_values(by=[\'ts_code\',\'trade_date_x\'],axis=0,ascending=[True,True])\nalldata.reset_index(drop=True, inplace=True)\nalldata.to_csv(\'C:/quant/daydate/summary/totalsummary.csv\') \nalldata'

In [58]:
%%time
S=Salldata
pd.isnull(S).sum()
S['date']=S.trade_date_x.astype(str)
S.date=S.date.str.split('.', 2).str[0]
S.date=pd.to_datetime(S.date)
S.open=S.open.fillna(method='ffill')
S.close=S.close.fillna(method='ffill') #防停牌无数据
S.high=S.high.fillna(method='ffill')
S.low=S.low.fillna(method='ffill')
#S.amount=S.amount.fillna(0,inplace=True)


latestday=S.date.max()
S.adj_factor.fillna(1,inplace=True)
S.loc[S['date']==latestday,'now_adj']=S['adj_factor'] # 最新复权因子
S.now_adj=S.now_adj.fillna(method='bfill')

#S.loc[S['ts_code']==S['ts_code'].shift(1),'now_adj']=S.now_adj.shift(1) # 最新复权因子
S['pre_close_qfq'] = S['pre_close'] * S['adj_factor'] / S.now_adj
S['high_qfq'] = S['high'] * S['adj_factor'] / S.now_adj
S['low_qfq'] = S['low'] * S['adj_factor'] / S.now_adj
S['close_qfq'] = S['close'] * S['adj_factor'] / S.now_adj  # 前复权 当日收盘价 × 当日复权因子 / 最新复权因子
#alldata.to_csv('C:/quant/index/2020/test.csv') 

S

Wall time: 7.12 s

,ts_code,trade_date_x,open,high,low,close,pre_close,change,pct_chg,vol,...,sell_elg_amount,net_mf_vol,net_mf_amount,adj_factor,date,now_adj,pre_close_qfq,high_qfq,low_qfq,close_qfq
0,000001.SZ,20170103,9.11,9.18,9.09,9.16,9.10,0.06,0.6600,459840.49,...,11939.93,71350,6531.67,104.758,2017-01-03,111.048,8.584556,8.660025,8.575123,8.641158
1,000001.SZ,20170104,9.15,9.18,9.14,9.16,9.16,0.00,0.0000,449329.53,...,16185.19,-6884,-608.63,104.758,2017-01-04,111.048,8.641158,8.660025,8.622291,8.641158
2,000001.SZ,20170105,9.17,9.18,9.15,9.17,9.16,0.01,0.1100,344372.91,...,6128.81,17325,1604.98,104.758,2017-01-05,111.048,8.641158,8.660025,8.631724,8.650591
3,000001.SZ,20170106,9.17,9.17,9.11,9.13,9.17,-0.04,-0.4400,358154.20,...,6910.19,-137025,-12502.51,104.758,2017-01-06,111.048,8.650591,8.650591,8.593990,8.612857
4,000001.SZ,20170109,9.13,9.17,9.11,9.15,9.13,0.02,0.2200,361081.57,...,8817.27,-38202,-3471.15,104.758,2017-01-09,111.048,8.612857,8.650591,8.593990,8.631724
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2345247,688981.SH,20201102,63.44,63.47,60.35,62.65,62.24,0.41,0.6587,511623.09,...,78428.69,-20038,-11856.99,1.000,2020-11-02,1.000,62.240000,63.470000,60.350000,62.650000
2345248,688981.SH,20201103,62.50,65.47,62.34,64.56,62.65,1.91,3.0487,550197.05,...,65476.69,51522,33595.56,1.000,2020-11-03,1.000,62.650000,65.470000,62.340000,64.560000
2345249,688981.SH,20201104,64.20,65.25,62.51,63.00,64.56,-1.56,-2.4164,460192.42,...,58296.44,-42276,-26532.14,1.000,2020-11-04,1.000,64.560000,65.250000,62.510000,63.000000
2345250,688981.SH,20201105,65.00,65.50,63.56,64.84,63.00,1.84,2.9206,414596.41,...,47270.95,49461,32197.90,1.000,2020-11-05,1.000,63.000000,65.500000,63.560000,64.840000
2345251,688981.SH,20201106,64.59,65.65,64.02,64.95,64.84,0.11,0.1696,358663.55,...,57705.37,16287,10816.59,1.000,2020-11-06,1.000,64.840000,65.650000,64.020000,64.950000

In [59]:
%%time
from scipy.stats import rankdata
df=S[S['ts_code'].notna()]

close=df.close_qfq
diff, dea, my_macd = talib.MACD(close,
                                             fastperiod=12,
                                             slowperiod=26,
#获取均线的数据，通过timeperiod参数来分别获取 5,10,20 日均线的数据。
                                             signalperiod=9)
SMA5=talib.SMA(close,timeperiod=5)
SMA10=talib.SMA(close,timeperiod=10)
SMA20=talib.SMA(close,timeperiod=20)
SMA60=talib.SMA(close,timeperiod=60)
SMA120=talib.SMA(close,timeperiod=120)

EMA5=talib.EMA(close,timeperiod=5)
EMA10=talib.EMA(close,timeperiod=10)
EMA20=talib.EMA(close,timeperiod=20)
EMA60=talib.EMA(close,timeperiod=60)
EMA120=talib.EMA(close,timeperiod=120)

df['diff']=diff
df['dea']=dea
df['MACD']=my_macd
df['SMA5']=SMA5
df['SMA10']=SMA10
df['SMA20']=SMA20
df['SMA60']=SMA60
df['SMA120']=SMA120

df['EMA5']=EMA5
df['EMA10']=EMA10
df['EMA60']=EMA60
df['EMA120']=EMA120

df['EMA20']=EMA20
df['SMACD-K']=(diff-dea)/dea
df['C/S']=(close/SMA20-1)*100
df['M/L']=(SMA60/SMA120-1)*100
df['S/M']=(SMA20/SMA60-1)*100
df.reset_index(drop=True, inplace=True)

df.loc[df['ts_code'] == df['ts_code'].shift(4),'Chg5D']= (df.close_qfq/df.close_qfq.shift(4)-1)*100
df.loc[df['ts_code'] == df['ts_code'].shift(9),'Chg10D']= (df.close_qfq/df.close_qfq.shift(9)-1)*100
df.loc[df['ts_code'] == df['ts_code'].shift(19),'Chg20D']= (df.close_qfq/df.close_qfq.shift(19)-1)*100
df.loc[df['ts_code'] == df['ts_code'].shift(59),'Chg60D']= (df.close_qfq/df.close_qfq.shift(59)-1)*100
df.loc[df['ts_code'] == df['ts_code'].shift(119),'Chg120D']= (df.close_qfq/df.close_qfq.shift(119)-1)*100

df['ATR'] = talib.ATR(df.high.values,df.low.values,df.pre_close.values, timeperiod=20)


df.fillna(0,inplace=True) #去除null
df.loc[(df['close_qfq']>df['EMA20']) & (df['close_qfq']>df['SMA20']) & (df['SMA20']>df['SMA20'].shift(19)),'kl1']=1 #破线拐头
df.loc[(df['EMA20']>df['EMA60']) & (df['close_qfq']>df['EMA20'].shift(19)),'K2']=1 #双均线交叉
df.loc[(df['EMA20']>df['SMA60']) & (df['close_qfq']>df['EMA20'].shift(19)),'K3']=1 
df.loc[(df['SMA20']>df['EMA60']) & (df['close_qfq']>df['SMA20'].shift(19)),'K4']=1 
df.loc[(df['SMA20']>df['SMA60']) & (df['close_qfq']>df['SMA20'].shift(19)),'K5']=1 

df.loc[(df['close_qfq']<df['EMA20']) & (df['close_qfq']<df['SMA20']) & (df['SMA20']<df['SMA20'].shift(19)),'kl1']=-1 #空头方向破线拐头
df.loc[(df['EMA20']<df['EMA60']) & (df['close_qfq']<df['EMA20'].shift(19)),'K2']=-1 #双均线交叉
df.loc[(df['EMA20']<df['SMA60']) & (df['close_qfq']<df['EMA20'].shift(19)),'K3']=-1 
df.loc[(df['SMA20']<df['EMA60']) & (df['close_qfq']<df['SMA20'].shift(19)),'K4']=-1 
df.loc[(df['SMA20']<df['SMA60']) & (df['close_qfq']<df['SMA20'].shift(19)),'K5']=-1 
df.fillna(0,inplace=True) #去除null
df['trendscore-L']=(df.kl1+df.K2+df.K3+df.K4+df.K5)

df.loc[(df['close_qfq']>df['EMA10']) & (df['close_qfq']>df['SMA10']) & (df['SMA10']>df['SMA10'].shift(19)),'ks1']=1 #破线拐头
df.loc[(df['EMA10']>df['EMA20']) & (df['close_qfq']>df['EMA10'].shift(19)),'KK2']=1 #双均线交叉
df.loc[(df['EMA10']>df['SMA20']) & (df['close_qfq']>df['EMA10'].shift(19)),'KK3']=1 
df.loc[(df['SMA10']>df['EMA20']) & (df['close_qfq']>df['SMA10'].shift(19)),'KK4']=1 
df.loc[(df['SMA10']>df['SMA20']) & (df['close_qfq']>df['SMA10'].shift(19)),'KK5']=1 

df.loc[(df['close_qfq']<df['EMA10']) & (df['close_qfq']<df['SMA10']) & (df['SMA10']<df['SMA10'].shift(19)),'ks1']=-1 #空头方向破线拐头
df.loc[(df['EMA10']<df['EMA20']) & (df['close_qfq']<df['EMA10'].shift(19)),'KK2']=-1 #双均线交叉
df.loc[(df['EMA10']<df['SMA20']) & (df['close_qfq']<df['EMA10'].shift(19)),'KK3']=-1 
df.loc[(df['SMA10']<df['EMA20']) & (df['close_qfq']<df['SMA10'].shift(19)),'KK4']=-1 
df.loc[(df['SMA10']<df['SMA20']) & (df['close_qfq']<df['SMA10'].shift(19)),'KK5']=-1 
df.fillna(0,inplace=True) #去除null
df['trendscore-S']=(df.ks1+df.KK2+df.KK3+df.KK4+df.KK5)
df = pd.merge(df, ISindex, how='left',on='ts_code') 

df=df[['date','ts_code','pre_close_qfq','close_qfq','high_qfq','low_qfq','amount','pct_chg','ATR','Chg5D','Chg20D','Chg60D','Chg120D','C/S','S/M','M/L','kl1','trendscore-L','SMA20','SMA60','SMA120','EMA20','EMA60','EMA120']]

df.head(10)

Wall time: 55.1 s

,date,ts_code,pre_close_qfq,close_qfq,high_qfq,low_qfq,amount,pct_chg,ATR,Chg5D,...,S/M,M/L,kl1,trendscore-L,SMA20,SMA60,SMA120,EMA20,EMA60,EMA120
0,2017-01-03,000001.SZ,8.584556,8.641158,8.660025,8.575123,420595.176,0.66,0.0,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,2017-01-04,000001.SZ,8.641158,8.641158,8.660025,8.622291,411503.444,0.00,0.0,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,2017-01-05,000001.SZ,8.641158,8.650591,8.660025,8.631724,315769.693,0.11,0.0,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,2017-01-06,000001.SZ,8.650591,8.612857,8.650591,8.593990,327176.433,-0.44,0.0,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,2017-01-09,000001.SZ,8.612857,8.631724,8.650591,8.593990,329994.604,0.22,0.0,-0.109170,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,2017-01-10,000001.SZ,8.631724,8.631724,8.641158,8.622291,220575.131,0.00,0.0,-0.109170,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6,2017-01-11,000001.SZ,8.631724,8.622291,8.650591,8.612857,277553.207,-0.11,0.0,-0.327154,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7,2017-01-12,000001.SZ,8.622291,8.631724,8.650591,8.612857,391869.402,0.11,0.0,0.219058,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8,2017-01-13,000001.SZ,8.631724,8.641158,8.669458,8.603423,397601.906,0.11,0.0,0.109290,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9,2017-01-16,000001.SZ,8.641158,8.622291,8.641158,8.556255,623025.820,-0.22,0.0,-0.109290,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [60]:
df
df.ts_code=df.ts_code.str.split('.',2).str[0]
df4=pd.merge(df,L2stocklist,how='left',on='ts_code')
df4.drop(['index_code','level'],axis=1)
BBStock=df4[df4['ts_code'].notna()]
BBStock.fillna(0,inplace=True)
BBStock.loc[BBStock.close_qfq>=BBStock.pre_close_qfq,'Signal']=0
BBStock.loc[BBStock.close_qfq<BBStock.pre_close_qfq,'Signal']=1
BBStock['ChangeSignal']=BBStock.Signal.diff().abs()
BBStock.ChangeSignal.fillna(0,inplace=True) #解决首行0
BBStock['BBperiod']=BBStock.groupby('ts_code').ChangeSignal.cumsum()

#个股级别日线涨跌周期

high_qfq = BBStock.groupby(['ts_code','stock_name','BBperiod'])['high_qfq'].max().rename('high_qfq').reset_index()
low_qfq = BBStock.groupby(['ts_code','stock_name','BBperiod'])['low_qfq'].min().rename('low_qfq').reset_index()
amount = BBStock.groupby(['ts_code','stock_name','BBperiod'])['amount'].sum().rename('amount').reset_index()
pre_close_qfq = BBStock.groupby(['ts_code','stock_name','BBperiod'])['pre_close_qfq'].first().rename('pre_close_qfq').reset_index()
close_qfq = BBStock.groupby(['ts_code','stock_name','BBperiod'])['close_qfq'].last().rename('close_qfq').reset_index()
lastperiod=BBStock.groupby(['ts_code','stock_name']).BBperiod.max().rename('lastbar')

BBS2 = pd.merge(pre_close_qfq,close_qfq,how='left',on=('ts_code','stock_name','BBperiod')) 
BBS2 = pd.merge(BBS2,high_qfq,how='left',on=('ts_code','stock_name','BBperiod')) 
BBS2 = pd.merge(BBS2,low_qfq,how='left',on=('ts_code','stock_name','BBperiod')) 
BBS2 = pd.merge(BBS2,amount,how='left',on=('ts_code','stock_name','BBperiod')) 
BBS2 = pd.merge(BBS2,lastperiod,how='left',on=('ts_code','stock_name')) 

close2=BBS2.close_qfq.values
#swsf.date=swsf.date.values

diff, dea, my_macd = talib.MACD(close2,
                                             fastperiod=12,
                                             slowperiod=26,
#获取均线的数据，通过timeperiod参数来分别获取 5,10,20 日均线的数据。
                                             signalperiod=9)
BBS2['D-diff']=diff
BBS2['D-dea']=dea
BBS2['D-MACD']=my_macd
BBS2=BBS2[BBS2['BBperiod']==BBS2['lastbar']]
BBS2 = BBS2.sort_values(by=['D-MACD'],axis=0,ascending=[False])

#BBS2.to_csv('C:/Users/atianth/Desktop/BBtest2.csv',index=False,encoding='utf-8-sig') 
BBS2

,ts_code,stock_name,BBperiod,pre_close_qfq,close_qfq,high_qfq,low_qfq,amount,lastbar,D-diff,D-dea,D-MACD
1200177,688169,0,91.0,831.99,892.00,892.00,818.00,1027110.544,91.0,92.745021,71.123152,21.621869
1206141,688788,0,6.0,204.30,206.86,208.55,202.01,290305.564,6.0,48.179214,30.801106,17.378108
1205332,688536,0,11.0,315.77,347.00,356.80,321.95,789411.368,11.0,78.960690,62.524869,16.435821
1193128,605111,新洁能,5.0,123.92,149.94,149.94,128.88,1752666.541,5.0,26.137965,12.125905,14.012061
711082,300896,爱美客,14.0,551.00,535.00,560.00,512.20,1504184.343,14.0,113.824156,101.066529,12.757628
...,...,...,...,...,...,...,...,...,...,...,...,...
854578,600519,贵州茅台,354.0,1721.90,1700.62,1731.59,1690.00,3932702.367,354.0,26.702887,36.115071,-9.412184
1198037,688095,0,21.0,313.97,305.50,316.80,296.70,519750.991,21.0,36.335502,46.548117,-10.212615
1192973,605018,长华股份,9.0,16.59,16.03,16.78,15.87,98152.870,9.0,-19.040761,-4.985958,-14.054803
1115602,603444,吉比特,364.0,478.88,457.50,482.98,448.41,1121604.717,364.0,-33.362823,-17.701733,-15.661090
1193346,605169,洪通燃气,4.0,26.42,25.88,26.67,25.50,398555.540,4.0,-37.478354,-8.763896,-28.714458

In [61]:
%%time
BBWStock=df4[df4['ts_code'].notna()]
BBWStock.fillna(0,inplace=True)
BBWStock['year']=BBWStock.date.dt.isocalendar().year
BBWStock['week']=BBWStock.date.dt.isocalendar().week
high_qfq = BBWStock.groupby(['ts_code','stock_name','year','week'])['high_qfq'].max().rename('high_qfq').reset_index()
low_qfq = BBWStock.groupby(['ts_code','stock_name','year','week'])['low_qfq'].min().rename('low_qfq').reset_index()
amount = BBWStock.groupby(['ts_code','stock_name','year','week'])['amount'].sum().rename('amount').reset_index()
pre_close_qfq1 = BBWStock.groupby(['ts_code','stock_name','year','week'])['pre_close_qfq'].first().rename('pre_close_qfq').reset_index()
close1 = BBWStock.groupby(['ts_code','stock_name','year','week'])['close_qfq'].last().rename('close_qfq').reset_index()

BBWS2 = pd.merge(pre_close_qfq1,close1,how='left',on=('ts_code','stock_name','year','week')) 
BBWS2 = pd.merge(BBWS2,high_qfq,how='left',on=('ts_code','stock_name','year','week')) 
BBWS2 = pd.merge(BBWS2,low_qfq,how='left',on=('ts_code','stock_name','year','week')) 
BBWS2 = pd.merge(BBWS2,amount,how='left',on=('ts_code','stock_name','year','week')) 

BBWS2.loc[BBWS2.close_qfq>=BBWS2.pre_close_qfq,'Signal']=0
BBWS2.loc[BBWS2.close_qfq<BBWS2.pre_close_qfq,'Signal']=1
BBWS2['ChangeSignal']=BBWS2.Signal.diff().abs()
BBWS2.ChangeSignal.fillna(0,inplace=True) #解决首行0
BBWS2['BBperiod']=BBWS2.groupby(['ts_code','stock_name']).ChangeSignal.cumsum()

high_qfq2 = BBWS2.groupby(['ts_code','stock_name','BBperiod'])['high_qfq'].max().rename('high_qfq').reset_index()
low_qfq2 = BBWS2.groupby(['ts_code','stock_name','BBperiod'])['low_qfq'].min().rename('low_qfq').reset_index()
amount2 = BBWS2.groupby(['ts_code','stock_name','BBperiod'])['amount'].sum().rename('amount').reset_index()
pre_close_qfq2 = BBWS2.groupby(['ts_code','stock_name','BBperiod'])['pre_close_qfq'].first().rename('pre_close_qfq').reset_index()
close2 = BBWS2.groupby(['ts_code','stock_name','BBperiod'])['close_qfq'].last().rename('close_qfq').reset_index()
lastperiod=BBWS2.groupby(['ts_code','stock_name']).BBperiod.max().rename('lastbar')


BBWS3 = pd.merge(pre_close_qfq2,close2,how='left',on=('ts_code','stock_name','BBperiod')) 
BBWS3 = pd.merge(BBWS3,high_qfq2,how='left',on=('ts_code','stock_name','BBperiod')) 
BBWS3 = pd.merge(BBWS3,low_qfq2,how='left',on=('ts_code','stock_name','BBperiod')) 
BBWS3 = pd.merge(BBWS3,amount2,how='left',on=('ts_code','stock_name','BBperiod')) 
BBWS3 = pd.merge(BBWS3,lastperiod,how='left',on=('ts_code','stock_name')) 

close3=BBWS3.close_qfq.values
#swsf.date=swsf.date.values

diff, dea, my_macd = talib.MACD(close3,
                                             fastperiod=12,
                                             slowperiod=26,
#获取均线的数据，通过timeperiod参数来分别获取 5,10,20 日均线的数据。
                                             signalperiod=9)
BBWS3['W-diff']=diff
BBWS3['W-dea']=dea
BBWS3['W-MACD']=my_macd
BBWS3=BBWS3[BBWS3['BBperiod']==BBWS3['lastbar']]
BBWS3 = BBWS3.sort_values(by=['W-MACD'],axis=0,ascending=[False])

BBWS3

Wall time: 41.3 s

,ts_code,stock_name,BBperiod,pre_close_qfq,close_qfq,high_qfq,low_qfq,amount,lastbar,W-diff,W-dea,W-MACD
157175,300896,爱美客,3.0,415.00,535.00,577.49,410.00,7594989.768,3.0,78.115217,26.315452,51.799765
265713,688536,0,5.0,261.05,347.00,356.80,245.81,2891796.881,5.0,56.501006,22.270865,34.230141
264481,688169,0,21.0,600.24,892.00,892.00,590.00,4374310.576,21.0,129.683133,95.728312,33.954821
263964,688095,0,4.0,270.00,305.50,317.60,268.56,1346527.925,4.0,59.955880,31.085268,28.870613
265922,688788,0,2.0,189.49,206.86,213.79,187.10,2124891.882,2.0,27.696928,5.320847,22.376081
...,...,...,...,...,...,...,...,...,...,...,...,...
265567,688408,0,5.0,123.60,153.11,159.80,120.52,1589789.671,5.0,8.005731,26.960463,-18.954731
245697,603444,吉比特,68.0,470.25,457.50,482.98,445.18,2004283.899,68.0,69.789189,91.371193,-21.582004
263221,688013,0,4.0,35.67,38.27,39.25,34.35,269791.887,4.0,-23.192104,-0.772756,-22.419349
263278,688017,0,7.0,75.40,97.33,99.80,74.01,981592.146,7.0,-32.123088,-9.507244,-22.615844
156833,300842,帝科股份,10.0,61.49,71.21,76.08,60.89,1851444.750,10.0,-37.519758,-6.224284,-31.295474

In [62]:
%%time
BBMStock=df4[df4['ts_code'].notna()]
BBMStock.fillna(0,inplace=True)
BBMStock['year']=BBMStock.date.dt.isocalendar().year
BBMStock['month']=BBMStock.date.dt.month
high_qfq = BBMStock.groupby(['ts_code','stock_name','year','month'])['high_qfq'].max().rename('high_qfq').reset_index()
low_qfq = BBMStock.groupby(['ts_code','stock_name','year','month'])['low_qfq'].min().rename('low_qfq').reset_index()
amount = BBMStock.groupby(['ts_code','stock_name','year','month'])['amount'].sum().rename('amount').reset_index()
pre_close_qfq1 = BBMStock.groupby(['ts_code','stock_name','year','month'])['pre_close_qfq'].first().rename('pre_close_qfq').reset_index()
close1 = BBMStock.groupby(['ts_code','stock_name','year','month'])['close_qfq'].last().rename('close_qfq').reset_index()

BBMS2 = pd.merge(pre_close_qfq1,close1,how='left',on=('ts_code','stock_name','year','month')) 
BBMS2 = pd.merge(BBMS2,high_qfq,how='left',on=('ts_code','stock_name','year','month')) 
BBMS2 = pd.merge(BBMS2,low_qfq,how='left',on=('ts_code','stock_name','year','month')) 
BBMS2 = pd.merge(BBMS2,amount,how='left',on=('ts_code','stock_name','year','month')) 

BBMS2.loc[BBMS2.close_qfq>=BBMS2.pre_close_qfq,'Signal']=0
BBMS2.loc[BBMS2.close_qfq<BBMS2.pre_close_qfq,'Signal']=1
BBMS2['ChangeSignal']=BBMS2.Signal.diff().abs()
BBMS2.ChangeSignal.fillna(0,inplace=True) #解决首行0
BBMS2['BBperiod']=BBMS2.groupby(['ts_code','stock_name']).ChangeSignal.cumsum()

high_qfq2 = BBMS2.groupby(['ts_code','stock_name','BBperiod'])['high_qfq'].max().rename('high_qfq').reset_index()
low_qfq2 = BBMS2.groupby(['ts_code','stock_name','BBperiod'])['low_qfq'].min().rename('low_qfq').reset_index()
amount2 = BBMS2.groupby(['ts_code','stock_name','BBperiod'])['amount'].sum().rename('Mamount').reset_index()
pre_close_qfq2 = BBMS2.groupby(['ts_code','stock_name','BBperiod'])['pre_close_qfq'].first().rename('pre_close_qfq').reset_index()
close2 = BBMS2.groupby(['ts_code','stock_name','BBperiod'])['close_qfq'].last().rename('close_qfq').reset_index()
lastperiod=BBMS2.groupby(['ts_code','stock_name']).BBperiod.max().rename('lastbar')

BBMS3 = pd.merge(pre_close_qfq2,close2,how='left',on=('ts_code','stock_name','BBperiod')) 
BBMS3 = pd.merge(BBMS3,high_qfq2,how='left',on=('ts_code','stock_name','BBperiod')) 
BBMS3 = pd.merge(BBMS3,low_qfq2,how='left',on=('ts_code','stock_name','BBperiod')) 
BBMS3 = pd.merge(BBMS3,amount2,how='left',on=('ts_code','stock_name','BBperiod')) 
BBMS3 = pd.merge(BBMS3,lastperiod,how='left',on=('ts_code','stock_name')) 
BBMS3 = BBMS3.sort_values(by=['ts_code','BBperiod'],axis=0,ascending=[True,True])
BBMS3['LastMonthK']=BBMS3.close_qfq.shift(1)/BBMS3.high_qfq.shift(1)
BBMS3['CurMonthK']=BBMS3.close_qfq/BBMS3.high_qfq


close3=BBMS3.close_qfq.values
#swsf.date=swsf.date.values

diff, dea, my_macd = talib.MACD(close3,
                                             fastperiod=12,
                                             slowperiod=26,
#获取均线的数据，通过timeperiod参数来分别获取 5,10,20 日均线的数据。
                                             signalperiod=9)
BBMS3['M-diff']=diff
BBMS3['M-dea']=dea
BBMS3['M-MACD']=my_macd
BBMS3=BBMS3[BBMS3['BBperiod']==BBMS3['lastbar']]
BBMS3 = BBMS3.sort_values(by=['M-MACD'],axis=0,ascending=[False])

BBMS3

Wall time: 36.9 s

,ts_code,stock_name,BBperiod,pre_close_qfq,close_qfq,high_qfq,low_qfq,Mamount,lastbar,LastMonthK,CurMonthK,M-diff,M-dea,M-MACD
44203,600519,贵州茅台,11.0,1668.500000,1700.62,1750.62,1600.00,9.836891e+07,11.0,0.912746,0.971439,381.226873,235.551164,145.675709
62098,688169,0,5.0,375.398406,892.00,892.00,376.00,2.339896e+07,5.0,0.912326,1.000000,122.527030,54.901925,67.625106
36697,300841,康华生物,2.0,462.000000,462.39,488.60,441.10,1.839790e+06,2.0,0.463855,0.946357,90.799392,33.355808,57.443585
36420,300782,卓胜微,7.0,377.800000,483.00,486.18,379.00,2.096359e+07,7.0,0.782405,0.993459,99.350717,57.065315,42.285402
62005,688111,0,5.0,327.510000,339.00,348.88,311.22,2.121011e+06,5.0,0.751170,0.971681,66.332210,27.472030,38.860180
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36257,300752,隆利科技,4.0,25.720000,32.75,35.00,23.53,6.635378e+06,4.0,0.860201,0.935714,0.080485,27.450269,-27.369784
36306,300761,立华股份,5.0,35.030000,36.09,37.43,33.79,1.099587e+06,5.0,0.778617,0.964200,-3.440972,24.488291,-27.929263
62108,688178,0,6.0,37.090000,36.90,37.92,35.81,5.117719e+04,6.0,0.958150,0.973101,-22.967097,5.029833,-27.996930
36427,300783,三只松鼠,7.0,53.880000,53.10,55.37,51.30,6.480528e+05,7.0,0.888229,0.959003,-0.646315,28.885870,-29.532185
13,000001,平安银行,13.0,17.750000,17.64,18.50,17.22,9.751110e+06,13.0,0.945154,0.953514,NaN,NaN,NaN

In [63]:
StockReport=df4[['date','ts_code','stock_name','index_code','industry_name','close_qfq','Chg5D','Chg20D','Chg60D','Chg120D','C/S','S/M','M/L','kl1','trendscore-L']]
lastday=StockReport.date.max()
StockReport=StockReport[StockReport.date==lastday]
SDReport=BBS2[['ts_code','D-diff','D-dea','D-MACD']]
SWReport=BBWS3[['ts_code','W-diff','W-dea','W-MACD']]
SMReport=BBMS3[['ts_code','Mamount','M-diff','M-dea','M-MACD','LastMonthK','CurMonthK']]
StockReport=pd.merge(StockReport,SDReport,how='left',on=('ts_code'))
StockReport=pd.merge(StockReport,SWReport,how='left',on=('ts_code'))
StockReport=pd.merge(StockReport,SMReport,how='left',on=('ts_code'))

StockReport.to_csv('C:/quant/output/Stockoutput.csv',index=False,encoding='utf-8-sig') 
StockReport

,date,ts_code,stock_name,index_code,industry_name,close_qfq,Chg5D,Chg20D,Chg60D,Chg120D,...,D-MACD,W-diff,W-dea,W-MACD,Mamount,M-diff,M-dea,M-MACD,LastMonthK,CurMonthK
0,2020-11-06,000001,平安银行,801192,银行,17.64,0.056721,10.943396,28.759124,31.647960,...,0.059675,1.339360,1.030420,0.308940,9.751110e+06,NaN,NaN,NaN,0.945154,0.953514
1,2020-11-06,000002,万科A,801181,房地产开发,29.46,5.402504,4.062169,13.020994,17.815559,...,-0.010222,1.009070,0.976754,0.032316,1.129485e+07,3.733154,4.268694,-0.535540,0.963624,0.996280
2,2020-11-06,000004,国农科技,801151,化学制药,26.84,4.435798,11.138716,-5.559465,-20.000000,...,0.356557,0.279605,0.954706,-0.675101,2.348425e+06,0.942490,0.829247,0.113243,0.666378,0.963043
3,2020-11-06,000005,世纪星源,801162,环保工程及服务,2.61,2.755906,-5.090909,-11.224490,-2.611940,...,-0.008780,-0.187753,-0.230677,0.042924,8.270387e+04,-4.930948,-4.930489,-0.000460,0.821429,0.973881
4,2020-11-06,000006,深振业A,801181,房地产开发,5.83,1.039861,-18.347339,-30.179641,22.111757,...,-0.019389,0.248878,0.206229,0.042649,2.582123e+05,-0.912318,-1.371666,0.459347,0.785714,0.976549
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4044,2020-11-06,688598,NaN,NaN,NaN,123.50,4.061341,4.351500,22.546049,0.000000,...,0.878884,18.966558,13.395180,5.571378,2.348719e+06,9.518113,1.441675,8.076438,0.915027,0.981093
4045,2020-11-06,688599,NaN,NaN,NaN,16.67,0.421687,-3.137711,1.584400,0.000000,...,0.846674,-12.731439,-11.054869,-1.676570,1.338290e+06,-6.188198,-1.256537,-4.931661,0.886971,0.960807
4046,2020-11-06,688600,NaN,NaN,NaN,20.18,5.323591,-12.979733,-28.082680,0.000000,...,-0.237552,-6.711313,-8.040401,1.329088,6.683083e+04,-8.045768,-4.292017,-3.753751,0.661706,0.980087
4047,2020-11-06,688788,NaN,NaN,NaN,206.86,7.739583,0.000000,0.000000,0.000000,...,17.378108,27.696928,5.320847,22.376081,9.667242e+06,6.483790,-2.136856,8.620646,0.980087,0.828102
4048,2020-11-06,688981,NaN,NaN,NaN,64.95,3.671189,13.133600,-19.286691,0.000000,...,2.023345,4.845259,9.168575,-4.323317,5.542524e+07,6.116274,2.131299,3.984975,0.564975,0.989337